import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import test from 'node:test';
import { BillingService, type CreditPackage } from '../src/main/gateway/billing.ts';
import { GatewayService } from '../src/main/gateway/service.ts';
import { GatewayStore } from '../src/main/gateway/store.ts';

const packages:CreditPackage[]=[{id:'starter',name:'Starter credits',credits:20_000,priceId:'price_starter'}];

test('billing creates server-authenticated hosted checkout sessions',async()=>{let request:{url:string;authorization:string;body:string}|undefined;const billing=new BillingService('sk_test_server','whsec_test','https://foundry.test/success','https://foundry.test/cancel',packages,async(url,init)=>{request={url,authorization:String((init.headers as Record<string,string>).Authorization),body:String(init.body)};return new Response(JSON.stringify({id:'cs_test_1',url:'https://checkout.stripe.test/session'}),{status:200,headers:{'Content-Type':'application/json'}})}),session=await billing.checkout({id:'account_1',email:'builder@example.com',credits:0,monthlySpendLimit:100,createdAt:new Date().toISOString()},'starter');assert.equal(session.url,'https://checkout.stripe.test/session');assert.equal(request?.url,'https://api.stripe.com/v1/checkout/sessions');assert.equal(request?.authorization,'Bearer sk_test_server');assert.match(request?.body??'',/metadata%5Baccount_id%5D=account_1/);assert.match(request?.body??'',/line_items%5B0%5D%5Bprice%5D=price_starter/)});

test('billing refuses a live Stripe key in test mode',async()=>{const billing=new BillingService('sk_live_server','whsec_test','https://foundry.test/success','https://foundry.test/cancel',packages,async()=>{throw new Error('Stripe must not be called.')},'test');assert.equal(billing.configured(),false);await assert.rejects(()=>billing.checkout({id:'account_1',email:'builder@example.com',credits:0,monthlySpendLimit:100,createdAt:new Date().toISOString()},'starter'),/live Stripe key, but test mode is required/)});

test('signed completed checkout grants credits exactly once',async()=>{const store=new GatewayStore(':memory:',100),session=await store.register('paid@example.com','a-secure-password'),secret='whsec_test',billing=new BillingService('sk_test',secret,'https://foundry.test/success','https://foundry.test/cancel',packages),gateway=new GatewayService(store,{},fetch,billing),event={id:'evt_1',type:'checkout.session.completed',data:{object:{id:'cs_1',payment_status:'paid',client_reference_id:session.account.id,amount_total:900,currency:'usd',metadata:{account_id:session.account.id,package_id:'starter',credits:'20000'}}}},raw=JSON.stringify(event),timestamp=Math.floor(Date.now()/1000),signature=createHmac('sha256',secret).update(`${timestamp}.${raw}`).digest('hex'),request={method:'POST',path:'/v1/billing/webhook',headers:{'stripe-signature':`t=${timestamp},v1=${signature}`},body:event,rawBody:raw};try{assert.equal((await gateway.handle(request)).status,200);assert.equal(store.authenticate(session.token).credits,20_100);assert.equal((await gateway.handle(request)).status,200);assert.equal(store.authenticate(session.token).credits,20_100);assert.equal(store.purchases(session.account.id).length,1)}finally{store.close()}});

test('forged or stale billing webhooks never grant credits',async()=>{const store=new GatewayStore(':memory:',100),session=await store.register('safe@example.com','a-secure-password'),billing=new BillingService('sk_test','whsec_real','https://foundry.test/success','https://foundry.test/cancel',packages),gateway=new GatewayService(store,{},fetch,billing),raw=JSON.stringify({id:'evt_fake',type:'checkout.session.completed',data:{object:{}}});try{const response=await gateway.handle({method:'POST',path:'/v1/billing/webhook',headers:{'stripe-signature':'t=1,v1=00'},body:{},rawBody:raw});assert.equal(response.status,400);assert.equal(store.authenticate(session.token).credits,100);assert.equal(store.purchases(session.account.id).length,0)}finally{store.close()}});

test('customer journey reaches a first managed build without a real charge',async()=>{const store=new GatewayStore(':memory:',0),webhookSecret='whsec_journey',billing=new BillingService('sk_test_journey',webhookSecret,'https://foundry.test/success','https://foundry.test/cancel',packages,async()=>new Response(JSON.stringify({id:'cs_test_journey',url:'https://checkout.stripe.com/c/pay/cs_test_journey',livemode:false}),{status:200,headers:{'Content-Type':'application/json'}}), 'test'),providerCalls:{authorization:string;body:Record<string,unknown>}[]=[],gateway=new GatewayService(store,{openai:'server-owned-openai-key'},async(_url,init)=>{providerCalls.push({authorization:String((init.headers as Record<string,string>).Authorization),body:JSON.parse(String(init.body))});return new Response(JSON.stringify({id:'resp_journey',usage:{input_tokens:20,output_tokens:10},output:[{type:'message',content:[{type:'output_text',text:'Your first managed build is ready.'}]}]}),{status:200,headers:{'Content-Type':'application/json'}})},billing);try{const registered=await gateway.handle({method:'POST',path:'/v1/auth/register',body:{email:'journey@example.com',password:'correct-horse-battery'}}),session=registered.body as {token:string;account:{id:string;credits:number}};assert.equal(registered.status,201);assert.equal(session.account.credits,0);const auth={authorization:`Bearer ${session.token}`},checkout=await gateway.handle({method:'POST',path:'/v1/billing/checkout',headers:auth,body:{packageId:'starter'}});assert.equal(checkout.status,201);assert.match(String((checkout.body as {url:string}).url),/^https:\/\/checkout\.stripe\.com\//);const event={id:'evt_journey',type:'checkout.session.completed',data:{object:{id:'cs_test_journey',payment_status:'paid',client_reference_id:session.account.id,amount_total:900,currency:'usd',metadata:{account_id:session.account.id,package_id:'starter',credits:'20000'}}}},raw=JSON.stringify(event),timestamp=Math.floor(Date.now()/1000),signature=createHmac('sha256',webhookSecret).update(`${timestamp}.${raw}`).digest('hex');assert.equal((await gateway.handle({method:'POST',path:'/v1/billing/webhook',headers:{'stripe-signature':`t=${timestamp},v1=${signature}`},body:event,rawBody:raw})).status,200);const refreshed=await gateway.handle({method:'GET',path:'/v1/me',headers:auth});assert.equal((refreshed.body as {account:{credits:number}}).account.credits,20_000);const build=await gateway.handle({method:'POST',path:'/v1/model/request',headers:auth,body:{provider:'openai',model:'gpt-5.6-sol',requestId:'journey_build_1234',payload:{model:'gpt-5.6-sol',input:'Build a desktop notes app.',max_output_tokens:40}}});assert.equal(build.status,200);assert.equal(providerCalls.length,1);assert.equal(providerCalls[0].authorization,'Bearer server-owned-openai-key');assert.equal(JSON.stringify(providerCalls[0]).includes(session.token),false);assert.ok(store.authenticate(session.token).credits<20_000)}finally{store.close()}});
