import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import test from 'node:test';
import { BillingService, type CreditPackage } from '../src/main/gateway/billing.ts';
import { GatewayService } from '../src/main/gateway/service.ts';
import { GatewayStore } from '../src/main/gateway/store.ts';

const packages:CreditPackage[]=[{id:'starter',name:'Starter credits',credits:20_000,priceId:'price_starter'}];

test('billing creates server-authenticated hosted checkout sessions',async()=>{let request:{url:string;authorization:string;body:string}|undefined;const billing=new BillingService('sk_test_server','whsec_test','https://foundry.test/success','https://foundry.test/cancel',packages,async(url,init)=>{request={url,authorization:String((init.headers as Record<string,string>).Authorization),body:String(init.body)};return new Response(JSON.stringify({id:'cs_test_1',url:'https://checkout.stripe.test/session'}),{status:200,headers:{'Content-Type':'application/json'}})}),session=await billing.checkout({id:'account_1',email:'builder@example.com',credits:0,monthlySpendLimit:100,createdAt:new Date().toISOString()},'starter');assert.equal(session.url,'https://checkout.stripe.test/session');assert.equal(request?.url,'https://api.stripe.com/v1/checkout/sessions');assert.equal(request?.authorization,'Bearer sk_test_server');assert.match(request?.body??'',/metadata%5Baccount_id%5D=account_1/);assert.match(request?.body??'',/line_items%5B0%5D%5Bprice%5D=price_starter/)});

test('signed completed checkout grants credits exactly once',async()=>{const store=new GatewayStore(':memory:',100),session=await store.register('paid@example.com','a-secure-password'),secret='whsec_test',billing=new BillingService('sk_test',secret,'https://foundry.test/success','https://foundry.test/cancel',packages),gateway=new GatewayService(store,{},fetch,billing),event={id:'evt_1',type:'checkout.session.completed',data:{object:{id:'cs_1',payment_status:'paid',client_reference_id:session.account.id,amount_total:900,currency:'usd',metadata:{account_id:session.account.id,package_id:'starter',credits:'20000'}}}},raw=JSON.stringify(event),timestamp=Math.floor(Date.now()/1000),signature=createHmac('sha256',secret).update(`${timestamp}.${raw}`).digest('hex'),request={method:'POST',path:'/v1/billing/webhook',headers:{'stripe-signature':`t=${timestamp},v1=${signature}`},body:event,rawBody:raw};try{assert.equal((await gateway.handle(request)).status,200);assert.equal(store.authenticate(session.token).credits,20_100);assert.equal((await gateway.handle(request)).status,200);assert.equal(store.authenticate(session.token).credits,20_100);assert.equal(store.purchases(session.account.id).length,1)}finally{store.close()}});

test('forged or stale billing webhooks never grant credits',async()=>{const store=new GatewayStore(':memory:',100),session=await store.register('safe@example.com','a-secure-password'),billing=new BillingService('sk_test','whsec_real','https://foundry.test/success','https://foundry.test/cancel',packages),gateway=new GatewayService(store,{},fetch,billing),raw=JSON.stringify({id:'evt_fake',type:'checkout.session.completed',data:{object:{}}});try{const response=await gateway.handle({method:'POST',path:'/v1/billing/webhook',headers:{'stripe-signature':'t=1,v1=00'},body:{},rawBody:raw});assert.equal(response.status,400);assert.equal(store.authenticate(session.token).credits,100);assert.equal(store.purchases(session.account.id).length,0)}finally{store.close()}});
