import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { DatabaseSync } from 'node:sqlite';
import { prepareCapabilityDatabase } from '../src/main/capability-database.ts';

test('capability database stores isolated JSON values',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-db-')),db=await prepareCapabilityDatabase(join(root,'app.sqlite'));await db.set('tasks','one',{title:'Ship Foundry',done:false});assert.deepEqual(await db.get('tasks','one'),{title:'Ship Foundry',done:false});assert.equal((await db.list('tasks'))[0].key,'one');assert.equal(await db.get('notes','one'),null);await db.delete('tasks','one');assert.equal(await db.get('tasks','one'),null);db.close()});
test('capability database rejects unsafe keys and oversized values',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-db-limits-')),db=await prepareCapabilityDatabase(join(root,'app.sqlite'));await assert.rejects(db.set('../escape','key','value'),/namespace/);await assert.rejects(db.set('app','key','x'.repeat(1_000_001)),/smaller than 1 MB/);db.close()});
test('capability database versions legacy schemas and preserves a pre-migration backup',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-db-migrate-')),file=join(root,'app.sqlite'),legacy=new DatabaseSync(file);legacy.exec("CREATE TABLE legacy(value TEXT); INSERT INTO legacy VALUES('safe');");legacy.close();const db=await prepareCapabilityDatabase(file);await db.set('app','ready',true);db.close();const migrated=new DatabaseSync(file),version=(migrated.prepare('PRAGMA user_version').get() as {user_version:number}).user_version;migrated.close();assert.equal(version,1);const backups=await import('node:fs/promises').then(fs=>fs.readdir(join(root,'.foundry-backups')));assert.equal(backups.length,1)});
test('capability database restores the latest verified backup after corruption',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-db-recover-')),file=join(root,'app.sqlite'),db=await prepareCapabilityDatabase(file);await db.set('notes','one',{title:'Protected'});const backup=db.backup();db.close();assert.ok((await readFile(backup)).length>0);await writeFile(file,Buffer.from('not a sqlite database'));const recovered=await prepareCapabilityDatabase(file);assert.deepEqual(await recovered.get('notes','one'),{title:'Protected'});recovered.close()});
test('capability database remains bounded under sustained writes and rapid backups',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-db-stress-')),db=await prepareCapabilityDatabase(join(root,'app.sqlite'));await Promise.all(Array.from({length:1_000},(_,index)=>db.set('history',`item-${index}`,{index,text:`Clipboard entry ${index}`})));const rows=await db.list('history');assert.equal(rows.length,500);assert.equal(new Set(rows.map(row=>row.key)).size,500);for(let index=0;index<12;index++)db.backup();const backups=await import('node:fs/promises').then(fs=>fs.readdir(join(root,'.foundry-backups')));assert.equal(backups.length,5);db.close()});
