import assert from 'node:assert/strict';
import test from 'node:test';
import { CloudClient, PRODUCTION_GATEWAY_URL, resolveGatewayUrl } from '../src/main/cloud-client.ts';

test('packaged builds use the production gateway while development remains local',()=>{assert.equal(resolveGatewayUrl(undefined,true),PRODUCTION_GATEWAY_URL);assert.equal(resolveGatewayUrl(undefined,false),'http://127.0.0.1:8787');assert.equal(resolveGatewayUrl('https://cloud.example/'), 'https://cloud.example');assert.throws(()=>resolveGatewayUrl('http://cloud.example',true),/requires HTTPS/)});

test('cloud client authenticates and validates account data',async()=>{let request:{url:string;body:string}|undefined;const client=new CloudClient('https://cloud.example',async(url,init)=>{request={url,body:String(init?.body)};return new Response(JSON.stringify({token:'session-token',account:{id:'acct_1',email:'sean@example.com',credits:25000,monthlySpendLimit:25000,createdAt:'2026-07-27T00:00:00.000Z'}}),{status:201,headers:{'Content-Type':'application/json'}})}),result=await client.authenticate('Sean@example.com','long-password',true);assert.equal(request?.url,'https://cloud.example/v1/auth/register');assert.match(request?.body??'',/Sean@example.com/);assert.equal(result.account.credits,25000)});

test('cloud client preserves service errors and rejects untrusted checkout URLs',async()=>{const failing=new CloudClient('https://cloud.example',async()=>new Response(JSON.stringify({error:'Email or password is incorrect.'}),{status:401,headers:{'Content-Type':'application/json'}}));await assert.rejects(()=>failing.authenticate('x@example.com','bad-password',false),/Email or password is incorrect/);const unsafe=new CloudClient('https://cloud.example',async()=>new Response(JSON.stringify({url:'https://stripe.com.evil.example/session'}),{status:201,headers:{'Content-Type':'application/json'}}));await assert.rejects(()=>unsafe.checkout('token','starter'),/untrusted payment URL/)});

test('cloud client refreshes an authenticated account',async()=>{const client=new CloudClient('https://cloud.example',async(url,init)=>{assert.equal(url,'https://cloud.example/v1/me');assert.equal((init?.headers as Record<string,string>).Authorization,'Bearer session-token');return new Response(JSON.stringify({account:{id:'acct_1',email:'sean@example.com',credits:24000,monthlySpendLimit:25000,createdAt:'2026-07-27T00:00:00.000Z'}}),{status:200,headers:{'Content-Type':'application/json'}})});assert.equal((await client.account('session-token')).credits,24000)});

test('cloud client provisions restricted generated-app credentials',async()=>{let authorization='';const client=new CloudClient('https://cloud.example',async(_url,init)=>{authorization=String((init?.headers as Record<string,string>).Authorization);return new Response(JSON.stringify({token:'fapp_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN',credential:{id:'app_1',accountId:'acct_1',name:'App',provider:'openai',model:'gpt-5.6-sol',monthlyBudget:1000,requestsPerMinute:10,revoked:false,createdAt:new Date().toISOString(),lastUsedAt:null}}),{status:201,headers:{'Content-Type':'application/json'}})}),result=await client.createAppCredential('session-token',{name:'App',provider:'openai',model:'gpt-5.6-sol',monthlyBudget:1000,requestsPerMinute:10});assert.equal(authorization,'Bearer session-token');assert.match(result.token,/^fapp_/)});
