import assert from 'node:assert/strict';
import test from 'node:test';
import { GatewayStore } from '../src/main/gateway/store.ts';
import { GatewayService } from '../src/main/gateway/service.ts';
import { postgresSslOptions } from '../src/main/gateway/postgres-store.ts';

test('PostgreSQL TLS verifies certificates unless explicitly overridden',()=>{
 assert.deepEqual(postgresSslOptions({}),{rejectUnauthorized:true});
 assert.deepEqual(postgresSslOptions({FOUNDRY_DATABASE_TLS_INSECURE:'1'}),{rejectUnauthorized:false});
 assert.equal(postgresSslOptions({FOUNDRY_DATABASE_SSL:'0'}),false);
});

test('gateway accounts use sessions and idempotent credit reservations',async()=>{const store=new GatewayStore(':memory:',100);try{const created=await store.register('Sean@example.com','correct-horse-battery');assert.equal(created.account.email,'sean@example.com');assert.equal(store.authenticate(created.token).credits,100);const first=store.reserve(created.account.id,'request_12345678',40),duplicate=store.reserve(created.account.id,'request_12345678',40);assert.equal(first.id,duplicate.id);assert.equal(store.authenticate(created.token).credits,60);assert.equal(store.settle(created.account.id,first.id,25).settled,25);assert.equal(store.authenticate(created.token).credits,75);assert.equal(store.settle(created.account.id,first.id,10).settled,25)}finally{store.close()}});

test('gateway proxies with server credentials and settles measured usage',async()=>{const store=new GatewayStore(':memory:',1000);try{const session=await store.register('builder@example.com','a-secure-password'),requests:{url:string;authorization:string}[]=[];const service=new GatewayService(store,{openai:'server-secret'},async(input,init)=>{requests.push({url:input,authorization:String((init.headers as Record<string,string>).Authorization)});return new Response(JSON.stringify({id:'response_1',usage:{input_tokens:100,output_tokens:50},output:[]}),{status:200,headers:{'Content-Type':'application/json'}})}),response=await service.handle({method:'POST',path:'/v1/model/request',headers:{authorization:`Bearer ${session.token}`},body:{provider:'openai',model:'gpt-5.6-sol',requestId:'build_12345678',payload:{model:'gpt-5.6-sol',input:'Build an app',max_output_tokens:100}}});assert.equal(response.status,200);assert.equal(requests[0].authorization,'Bearer server-secret');assert.ok(store.authenticate(session.token).credits<1000)}finally{store.close()}});

test('gateway releases reserved credits when the provider fails',async()=>{const store=new GatewayStore(':memory:',1000);try{const session=await store.register('retry@example.com','a-secure-password');const service=new GatewayService(store,{openai:'server-secret'},async()=>new Response(JSON.stringify({error:{message:'temporary'}}),{status:500,headers:{'Content-Type':'application/json'}})),response=await service.handle({method:'POST',path:'/v1/model/request',headers:{authorization:`Bearer ${session.token}`},body:{provider:'openai',model:'gpt-5.6-sol',requestId:'failed_12345678',payload:{model:'gpt-5.6-sol',input:'Build'}}});assert.equal(response.status,502);assert.equal(store.authenticate(session.token).credits,1000)}finally{store.close()}});

test('persistent rate limits reject excess requests and reset by window',()=>{const store=new GatewayStore(':memory:',100);try{assert.deepEqual(store.consumeRateLimit('auth:127.0.0.1',2,60,120),{allowed:true,remaining:1,resetAt:180});assert.deepEqual(store.consumeRateLimit('auth:127.0.0.1',2,60,121),{allowed:true,remaining:0,resetAt:180});assert.deepEqual(store.consumeRateLimit('auth:127.0.0.1',2,60,122),{allowed:false,remaining:0,resetAt:180});assert.deepEqual(store.consumeRateLimit('auth:127.0.0.1',2,60,180),{allowed:true,remaining:1,resetAt:240})}finally{store.close()}});

test('production readiness fails closed without provider and billing configuration',async()=>{const store=new GatewayStore(':memory:',100);try{const service=new GatewayService(store,{},fetch,undefined,true);assert.deepEqual(await service.handle({method:'GET',path:'/health/live'}),{status:200,body:{status:'ok'}});assert.deepEqual(await service.handle({method:'GET',path:'/health/ready'}),{status:503,body:{status:'not_ready'}})}finally{store.close()}});

test('app credentials are scoped, metered, and never returned by list',async()=>{const store=new GatewayStore(':memory:',1000);try{const session=await store.register('publisher@example.com','a-secure-password'),service=new GatewayService(store,{openai:'server-secret'},async()=>new Response(JSON.stringify({id:'response_1',usage:{input_tokens:10,output_tokens:5},output:[{type:'message'}]}),{status:200,headers:{'Content-Type':'application/json'}})),created=await service.handle({method:'POST',path:'/v1/apps/credentials',headers:{authorization:`Bearer ${session.token}`},body:{name:'Meal planner production',provider:'openai',model:'gpt-5.6-sol',monthlyBudget:100,requestsPerMinute:5}});assert.equal(created.status,201);const token=String((created.body as {token:string}).token),credential=(created.body as {credential:{id:string}}).credential;assert.match(token,/^fapp_/);const listed=await service.handle({method:'GET',path:'/v1/apps/credentials',headers:{authorization:`Bearer ${session.token}`}});assert.equal(JSON.stringify(listed.body).includes(token),false);const response=await service.handle({method:'POST',path:'/v1/apps/model/request',headers:{authorization:`Bearer ${token}`},body:{requestId:'request_12345678',payload:{input:'Suggest dinner',max_output_tokens:10}}});assert.equal(response.status,200);assert.ok(store.appUsageThisMonth(credential.id)>0)}finally{store.close()}});

test('app credentials enforce provider scope, rate limits, and revocation',async()=>{const store=new GatewayStore(':memory:',1000);try{const session=await store.register('limits@example.com','a-secure-password'),service=new GatewayService(store,{openai:'server-secret'},async()=>new Response(JSON.stringify({usage:{input_tokens:1,output_tokens:1}}),{status:200,headers:{'Content-Type':'application/json'}})),created=await service.handle({method:'POST',path:'/v1/apps/credentials',headers:{authorization:`Bearer ${session.token}`},body:{name:'Restricted app',provider:'openai',model:'gpt-5.6-sol',monthlyBudget:100,requestsPerMinute:1}}),token=String((created.body as {token:string}).token),id=(created.body as {credential:{id:string}}).credential.id,bad=await service.handle({method:'POST',path:'/v1/apps/model/request',headers:{authorization:`Bearer ${token}`},body:{provider:'anthropic',requestId:'request_12345678',payload:{input:'hello'}}});assert.equal(bad.status,400);const limited=await service.handle({method:'POST',path:'/v1/apps/model/request',headers:{authorization:`Bearer ${token}`},body:{requestId:'request_abcdefgh',payload:{input:'hello'}}});assert.equal(limited.status,429);await service.handle({method:'DELETE',path:`/v1/apps/credentials/${id}`,headers:{authorization:`Bearer ${session.token}`}});const revoked=await service.handle({method:'POST',path:'/v1/apps/model/request',headers:{authorization:`Bearer ${token}`},body:{requestId:'request_revoked1',payload:{input:'hello'}}});assert.equal(revoked.status,401)}finally{store.close()}});
