import assert from 'node:assert/strict';
import test from 'node:test';
import { GatewayStore } from '../src/main/gateway/store.ts';
import { GatewayService } from '../src/main/gateway/service.ts';

test('gateway accounts use sessions and idempotent credit reservations',async()=>{const store=new GatewayStore(':memory:',100);try{const created=await store.register('Sean@example.com','correct-horse-battery');assert.equal(created.account.email,'sean@example.com');assert.equal(store.authenticate(created.token).credits,100);const first=store.reserve(created.account.id,'request_12345678',40),duplicate=store.reserve(created.account.id,'request_12345678',40);assert.equal(first.id,duplicate.id);assert.equal(store.authenticate(created.token).credits,60);assert.equal(store.settle(created.account.id,first.id,25).settled,25);assert.equal(store.authenticate(created.token).credits,75);assert.equal(store.settle(created.account.id,first.id,10).settled,25)}finally{store.close()}});

test('gateway proxies with server credentials and settles measured usage',async()=>{const store=new GatewayStore(':memory:',1000);try{const session=await store.register('builder@example.com','a-secure-password'),requests:{url:string;authorization:string}[]=[];const service=new GatewayService(store,{openai:'server-secret'},async(input,init)=>{requests.push({url:input,authorization:String((init.headers as Record<string,string>).Authorization)});return new Response(JSON.stringify({id:'response_1',usage:{input_tokens:100,output_tokens:50},output:[]}),{status:200,headers:{'Content-Type':'application/json'}})}),response=await service.handle({method:'POST',path:'/v1/model/request',headers:{authorization:`Bearer ${session.token}`},body:{provider:'openai',model:'gpt-5.6-sol',requestId:'build_12345678',payload:{model:'gpt-5.6-sol',input:'Build an app',max_output_tokens:100}}});assert.equal(response.status,200);assert.equal(requests[0].authorization,'Bearer server-secret');assert.ok(store.authenticate(session.token).credits<1000)}finally{store.close()}});

test('gateway releases reserved credits when the provider fails',async()=>{const store=new GatewayStore(':memory:',1000);try{const session=await store.register('retry@example.com','a-secure-password');const service=new GatewayService(store,{openai:'server-secret'},async()=>new Response(JSON.stringify({error:{message:'temporary'}}),{status:500,headers:{'Content-Type':'application/json'}})),response=await service.handle({method:'POST',path:'/v1/model/request',headers:{authorization:`Bearer ${session.token}`},body:{provider:'openai',model:'gpt-5.6-sol',requestId:'failed_12345678',payload:{model:'gpt-5.6-sol',input:'Build'}}});assert.equal(response.status,502);assert.equal(store.authenticate(session.token).credits,1000)}finally{store.close()}});

test('persistent rate limits reject excess requests and reset by window',()=>{const store=new GatewayStore(':memory:',100);try{assert.deepEqual(store.consumeRateLimit('auth:127.0.0.1',2,60,120),{allowed:true,remaining:1,resetAt:180});assert.deepEqual(store.consumeRateLimit('auth:127.0.0.1',2,60,121),{allowed:true,remaining:0,resetAt:180});assert.deepEqual(store.consumeRateLimit('auth:127.0.0.1',2,60,122),{allowed:false,remaining:0,resetAt:180});assert.deepEqual(store.consumeRateLimit('auth:127.0.0.1',2,60,180),{allowed:true,remaining:1,resetAt:240})}finally{store.close()}});

test('production readiness fails closed without provider and billing configuration',async()=>{const store=new GatewayStore(':memory:',100);try{const service=new GatewayService(store,{},fetch,undefined,true);assert.deepEqual(await service.handle({method:'GET',path:'/health/live'}),{status:200,body:{status:'ok'}});assert.deepEqual(await service.handle({method:'GET',path:'/health/ready'}),{status:503,body:{status:'not_ready'}})}finally{store.close()}});
