import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,mkdir,readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {ReleaseQualificationService} from '../src/main/release-qualification.ts';

test('release qualification verifies, packages, installs, launches, and cleans up',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-qualify-')),artifacts=join(root,'artifacts');await mkdir(artifacts);const installerPath=join(artifacts,'App Setup.exe'),checksumPath=`${installerPath}.sha256`,bytes=Buffer.from('installer');await writeFile(installerPath,bytes);await writeFile(checksumPath,`${createHash('sha256').update(bytes).digest('hex')}  App Setup.exe\n`);let commands=0;const result=await new ReleaseQualificationService({root:join(root,'runs'),verify:async()=>({passed:true,verifiedAt:new Date().toISOString(),checks:[{name:'Render',passed:true,detail:'Rendered'}]}),build:async()=>({installerPath,checksumPath,outputDirectory:artifacts,signed:false}),runner:async(file,args,options)=>{commands++;if(options.survivalMs)return{code:null,survived:true};const target=args.find(arg=>arg.startsWith('/D='))?.slice(3);assert.ok(target);await mkdir(target,{recursive:true});await writeFile(join(target,'Qualified App.exe'),Buffer.alloc(1_000_001));return{code:0}}}).run();assert.equal(result.passed,true);assert.equal(commands,2);assert.deepEqual(result.checks.map(check=>check.stage),['verify','package','checksum','install','launch','cleanup']);assert.equal((await readFile(installerPath)).equals(bytes),true)});
test('release qualification stops before packaging when workflow verification fails',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-qualify-fail-'));let builds=0;const result=await new ReleaseQualificationService({root,verify:async()=>({passed:false,verifiedAt:new Date().toISOString(),checks:[{name:'Workflow',passed:false,detail:'Button missing'}]}),build:async()=>{builds++;throw new Error('should not build')}}).run();assert.equal(result.passed,false);assert.equal(builds,0);assert.deepEqual(result.checks.map(check=>check.stage),['verify','cleanup'])});
test('release qualification bounds workflow verification time',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-qualify-timeout-'));let builds=0;const result=await new ReleaseQualificationService({root,verificationTimeoutMs:10,verify:()=>new Promise(()=>{}),build:async()=>{builds++;throw new Error('should not build')}}).run();assert.equal(result.passed,false);assert.equal(builds,0);assert.match(result.checks.find(check=>check.stage==='verify')?.detail??'',/verification timed out/i);assert.deepEqual(result.checks.map(check=>check.stage),['verify','cleanup'])});

test('packaging failures retain their stage and bounded diagnostic',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-qualify-package-'));const result=await new ReleaseQualificationService({root,verify:async()=>({passed:true,verifiedAt:new Date().toISOString(),checks:[]}),build:async()=>{throw new Error('x'.repeat(8_000))}}).run();const failure=result.checks.find(check=>!check.passed);assert.equal(failure?.stage,'package');assert.equal(failure?.detail.length,4_000)});

test('qualification launcher terminates the complete Windows process tree after the smoke interval',async()=>{const source=await readFile(join(process.cwd(),'src/main/release-qualification.ts'),'utf8');assert.match(source,/taskkill.*\/T.*\/F/s);assert.match(source,/survivalReached=true;void stopProcessTree\(child\.pid\)\.then\(\(\)=>finish\(\{code:null,survived:true\}\)\)/);assert.match(source,/if\(!survivalReached\)finish\(\{code,survived:false\}\)/)});
test('Windows qualification retries one transient first-launch exit',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-qualify-retry-')),artifacts=join(root,'artifacts');await mkdir(artifacts);const installerPath=join(artifacts,'App Setup.exe'),checksumPath=`${installerPath}.sha256`,bytes=Buffer.from('installer');await writeFile(installerPath,bytes);await writeFile(checksumPath,`${createHash('sha256').update(bytes).digest('hex')}  App Setup.exe\n`);let launches=0;const result=await new ReleaseQualificationService({root:join(root,'runs'),verify:async()=>({passed:true,verifiedAt:new Date().toISOString(),checks:[{name:'Render',passed:true,detail:'Rendered'}]}),build:async()=>({installerPath,checksumPath,outputDirectory:artifacts,signed:false,platform:'windows'}),runner:async(_file,args,options)=>{if(options.survivalMs){launches++;return launches===1?{code:1,survived:false}:{code:null,survived:true}}const target=args.find(arg=>arg.startsWith('/D='))?.slice(3);assert.ok(target);await mkdir(target,{recursive:true});await writeFile(join(target,'Qualified App.exe'),Buffer.alloc(1_000_001));return{code:0}}}).run();assert.equal(result.passed,true);assert.equal(launches,2);assert.match(result.checks.find(check=>check.stage==='launch')?.detail??'',/first-run retry/i)});
test('qualification launch strips Node and builder-only environment switches',async()=>{const source=await readFile(join(process.cwd(),'src/main/release-qualification.ts'),'utf8');assert.match(source,/applicationLaunchEnvironment\(\)/);for(const key of ['ELECTRON_RUN_AS_NODE','FOUNDRY_ELECTRON_BUILDER_CLI','ESBUILD_BINARY_PATH','NODE_OPTIONS','NODE_USE_SYSTEM_CA'])assert.match(source,new RegExp(`'${key}'`))});

test('qualification cleanup bounds retries and defers transient Windows file locks',async()=>{const source=await readFile(join(process.cwd(),'src/main/release-qualification.ts'),'utf8');assert.match(source,/rm\(resolvedTarget,\{recursive:true,force:true,maxRetries:2,retryDelay:500\}\)/);assert.match(source,/isTransientWindowsLock\(error\)/);assert.match(source,/scheduleDeferredRemove\(testRoot,this\.options\.root\)/)});

test('Linux qualification prepares and launches an AppImage artifact',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-qualify-linux-')),artifacts=join(root,'artifacts');await mkdir(artifacts);const installerPath=join(artifacts,'App.AppImage'),checksumPath=`${installerPath}.sha256`,bytes=Buffer.from('appimage');await writeFile(installerPath,bytes);await writeFile(checksumPath,`${createHash('sha256').update(bytes).digest('hex')}  App.AppImage\n`);let launches=0;const result=await new ReleaseQualificationService({root:join(root,'runs'),verify:async()=>({passed:true,verifiedAt:new Date().toISOString(),checks:[{name:'Render',passed:true,detail:'Rendered'}]}),build:async()=>({installerPath,checksumPath,outputDirectory:artifacts,signed:false,platform:'linux'}),runner:async(file,_args,options)=>{if(options.survivalMs){launches++;assert.match(file,/qualified\.AppImage$/);return{code:null,survived:true}}return{code:0}}}).run();assert.equal(result.passed,true);assert.equal(launches,1)});
