import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,mkdir,readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {ReleaseQualificationService} from '../src/main/release-qualification.ts';

test('release qualification verifies, packages, installs, launches, and cleans up',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-qualify-')),artifacts=join(root,'artifacts');await mkdir(artifacts);const installerPath=join(artifacts,'App Setup.exe'),checksumPath=`${installerPath}.sha256`,bytes=Buffer.from('installer');await writeFile(installerPath,bytes);await writeFile(checksumPath,`${createHash('sha256').update(bytes).digest('hex')}  App Setup.exe\n`);let commands=0;const result=await new ReleaseQualificationService({root:join(root,'runs'),verify:async()=>({passed:true,verifiedAt:new Date().toISOString(),checks:[{name:'Render',passed:true,detail:'Rendered'}]}),build:async()=>({installerPath,checksumPath,outputDirectory:artifacts,signed:false}),runner:async(file,args,options)=>{commands++;if(options.survivalMs)return{code:null,survived:true};const target=args.find(arg=>arg.startsWith('/D='))?.slice(3);assert.ok(target);await mkdir(target,{recursive:true});await writeFile(join(target,'Qualified App.exe'),Buffer.alloc(1_000_001));return{code:0}}}).run();assert.equal(result.passed,true);assert.equal(commands,2);assert.deepEqual(result.checks.map(check=>check.stage),['verify','package','checksum','install','launch','cleanup']);assert.equal((await readFile(installerPath)).equals(bytes),true)});
test('release qualification stops before packaging when workflow verification fails',async()=>{const root=await mkdtemp(join(tmpdir(),'foundry-qualify-fail-'));let builds=0;const result=await new ReleaseQualificationService({root,verify:async()=>({passed:false,verifiedAt:new Date().toISOString(),checks:[{name:'Workflow',passed:false,detail:'Button missing'}]}),build:async()=>{builds++;throw new Error('should not build')}}).run();assert.equal(result.passed,false);assert.equal(builds,0);assert.deepEqual(result.checks.map(check=>check.stage),['verify','cleanup'])});
