import test from 'node:test';
import assert from 'node:assert/strict';
import { behaviorRepairPrompt, failedVerificationChecks, mergeRepairResult, runBehaviorRepairLoop, runVisualRepairLoop, verificationStage, visualRepairPrompt } from '../src/main/reliability.ts';

const result={passed:false,verifiedAt:new Date(0).toISOString(),checks:[{name:'Compile',passed:true,detail:'Compiled.'},{name:'Workflow: click',passed:false,detail:'Could not find a visible button labeled Save note'}]};
const workflow=[{action:'click' as const,target:'Save note',value:''},{action:'assert_text' as const,target:'',value:'Saved'}];

test('reliability diagnostics identify failed checks and stage',()=>{assert.equal(failedVerificationChecks(result).length,1);assert.equal(verificationStage(result),'workflow')});
test('behavior repair prompt preserves the original request and required workflow',()=>{const prompt=behaviorRepairPrompt('Build a notes app',result,2,workflow);assert.match(prompt,/Repair attempt 2/);assert.match(prompt,/Build a notes app/);assert.match(prompt,/Save note/);assert.match(prompt,/real visible <button>/);assert.match(prompt,/Do not redesign/)});
test('repair result preserves the authoritative workflow',()=>{const merged=mergeRepairResult({message:'Built',filesChanged:['src/main.tsx'],iterations:2,workflow},{message:'Fixed',filesChanged:['src/styles.css'],iterations:3,workflow:[]},workflow);assert.deepEqual(merged.workflow,workflow);assert.deepEqual(merged.filesChanged,['src/main.tsx','src/styles.css']);assert.equal(merged.iterations,5)});
test('visual repair prompt protects working behavior',()=>{const prompt=visualRepairPrompt('Build a timer',['Button is clipped'],1);assert.match(prompt,/Button is clipped/);assert.match(prompt,/Preserve all working controls/)});
test('repair loop records diagnosis and stops after verification passes',async()=>{let repairs=0,verifications=0;const passed={passed:true,verifiedAt:new Date(1).toISOString(),checks:[{name:'Workflow',passed:true,detail:'Saved'}]};const loop=await runBehaviorRepairLoop({request:'Build a notes app',result:{message:'Built',filesChanged:[],iterations:1,workflow},workflow,verification:result,repair:async prompt=>{repairs++;assert.match(prompt,/Save note/);return{message:'Fixed',filesChanged:['src/main.tsx'],iterations:1,workflow}},verify:async()=>{verifications++;return passed}});assert.equal(repairs,1);assert.equal(verifications,1);assert.equal(loop.verification.passed,true);assert.equal(loop.attempts.length,1);assert.equal(loop.attempts[0]?.stage,'workflow');assert.equal(loop.attempts[0]?.progress,true)});
test('repair loop stops after two identical no-progress attempts',async()=>{let repairs=0;const loop=await runBehaviorRepairLoop({request:'Build it',result:{message:'Built',filesChanged:[],iterations:1,workflow},workflow,verification:result,maxAttempts:5,repair:async()=>{repairs++;return{message:'Tried',filesChanged:[],iterations:1,workflow}},verify:async()=>result});assert.equal(repairs,2);assert.equal(loop.attempts.length,2);assert.equal(loop.attempts.every(attempt=>!attempt.progress),true)});
test('visual repair automatically recovers behavior before reviewing again',async()=>{const passed={passed:true,verifiedAt:new Date(1).toISOString(),checks:[{name:'Workflow',passed:true,detail:'Saved'}]},visualFail={passed:false,issues:['Button is clipped']},visualPass={passed:true,issues:[]};let verifyCalls=0,behaviorRepairs=0,reviews=0;const loop=await runVisualRepairLoop({request:'Build it',result:{message:'Built',filesChanged:[],iterations:1,workflow},workflow,verification:passed,visual:visualFail,repairVisual:async()=>({message:'Styled',filesChanged:['src/styles.css'],iterations:1,workflow}),verify:async()=>++verifyCalls===1?result:passed,repairBehavior:async()=>{behaviorRepairs++;return{message:'Restored',filesChanged:['src/main.tsx'],iterations:1,workflow}},review:async()=>{reviews++;return visualPass}});assert.equal(behaviorRepairs,1);assert.equal(reviews,1);assert.equal(loop.verification.passed,true);assert.equal(loop.visual.passed,true);assert.equal(loop.attempts[0]?.behaviorRepairs.length,1)});
test('visual repair stops before another screenshot when behavior cannot be recovered',async()=>{let reviews=0;const loop=await runVisualRepairLoop({request:'Build it',result:{message:'Built',filesChanged:[],iterations:1,workflow},workflow,verification:result,visual:{passed:false,issues:['Overlap']},maxBehaviorAttempts:1,repairVisual:async()=>({message:'Styled',filesChanged:[],iterations:1,workflow}),verify:async()=>result,repairBehavior:async()=>({message:'Tried',filesChanged:[],iterations:1,workflow}),review:async()=>{reviews++;return{passed:true,issues:[]}}});assert.equal(reviews,0);assert.equal(loop.verification.passed,false);assert.equal(loop.attempts.length,1)});
