import {spawn} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
import {chmod,copyFile,mkdir,readFile,readdir,rm,stat} from 'node:fs/promises';
import {join,relative,resolve,sep} from 'node:path';
import type {InstallerResult} from './installer.ts';
import type {VerificationResult} from './agent.ts';

export type QualificationStage='verify'|'package'|'checksum'|'install'|'launch'|'cleanup';
export type QualificationCheck={stage:QualificationStage;passed:boolean;detail:string};
export type QualificationResult={id:string;passed:boolean;startedAt:string;completedAt:string;checks:QualificationCheck[];installerPath?:string};
type CommandResult={code:number|null;survived?:boolean};
type CommandRunner=(file:string,args:string[],options:{timeoutMs:number;survivalMs?:number;env?:NodeJS.ProcessEnv})=>Promise<CommandResult>;
type Options={root:string;verify:()=>Promise<VerificationResult>;build:(progress:(message:string)=>void)=>Promise<InstallerResult>;onProgress?:(message:string)=>void;runner?:CommandRunner;verificationTimeoutMs?:number};

export class ReleaseQualificationService{
  constructor(private readonly options:Options){const verify=options.verify;this.options.verify=()=>withTimeout(verify(),options.verificationTimeoutMs??90_000,'Application workflow verification timed out. Close any generated-app dialogs and try Release Check again.')}
  async run():Promise<QualificationResult>{
    const id=randomUUID(),startedAt=new Date().toISOString(),checks:QualificationCheck[]=[],testRoot=join(resolve(this.options.root),id),installRoot=join(testRoot,'installed'),dataRoot=join(testRoot,'data'),runner=this.options.runner??runCommand;let installerPath:string|undefined,stopped=false,installedToDisk=false,mountedMac=false,currentStage:QualificationStage='verify';
    await mkdir(testRoot,{recursive:true});
    try{
      this.progress('Verifying the generated application workflow…');const verification=await this.options.verify();checks.push({stage:'verify',passed:verification.passed,detail:verification.passed?`${verification.checks.length} workflow checks passed.`:verification.checks.filter(check=>!check.passed).map(check=>check.detail).join(' ')});stopped=!verification.passed;
      let installer:InstallerResult|undefined;if(!stopped){currentStage='package';this.progress('Building an isolated qualification installer…');installer=await this.options.build(message=>this.progress(message));installerPath=installer.installerPath;checks.push({stage:'package',passed:true,detail:`${installer.platform??'windows'} installer was produced.`});currentStage='checksum';const expected=(await readFile(installer.checksumPath,'utf8')).trim().split(/\s+/)[0]?.toLowerCase(),actual=createHash('sha256').update(await readFile(installer.installerPath)).digest('hex'),checksumPassed=expected===actual;checks.push({stage:'checksum',passed:checksumPassed,detail:checksumPassed?'Installer checksum matched.':'Installer checksum did not match.'});stopped=!checksumPassed}
      if(!stopped&&installer){currentStage='install';this.progress('Installing into an isolated temporary directory…');await mkdir(installRoot,{recursive:true});const platform=installer.platform??'windows';let installed:CommandResult;if(platform==='windows')installed=await runner(installer.installerPath,['/S',`/D=${installRoot}`],{timeoutMs:180_000});else if(platform==='macos'){installed=await runner('hdiutil',['attach','-nobrowse','-mountpoint',installRoot,installer.installerPath],{timeoutMs:180_000});mountedMac=installed.code===0}else{const target=join(installRoot,'qualified.AppImage');await copyFile(installer.installerPath,target);await chmod(target,0o755);installed={code:0}}installedToDisk=installed.code===0;checks.push({stage:'install',passed:installedToDisk,detail:installedToDisk?`${platform} artifact was prepared in isolation.`:`Installer exited with code ${installed.code}.`});stopped=!installedToDisk}
      if(!stopped&&installer){currentStage='launch';const platform=installer.platform??'windows',executable=platform==='linux'?join(installRoot,'qualified.AppImage'):await findApplicationExecutable(installRoot,platform);if(!executable){checks.push({stage:'launch',passed:false,detail:'Installed application executable was not found.'});stopped=true}else{this.progress('Launching the installed application smoke test…');const launchArgs=platform==='macos'?[]:[`--user-data-dir=${dataRoot}`],launchOptions={timeoutMs:20_000,survivalMs:4_000,env:applicationLaunchEnvironment()},firstLaunch=await runner(executable,launchArgs,launchOptions);let launched=firstLaunch,retried=false;if(!firstLaunch.survived&&platform==='windows'){retried=true;this.progress('Retrying the installed application after Windows completed first-run setup…');await delay(1_500);launched=await runner(executable,launchArgs,launchOptions)}checks.push({stage:'launch',passed:Boolean(launched.survived),detail:launched.survived?`Installed application launched and remained healthy${retried?' after a first-run retry':''}.`:`Installed application exited early with code ${launched.code}${retried?` after retry (first exit code ${firstLaunch.code})`:''}.`})}}
    }catch(error){checks.push({stage:currentStage,passed:false,detail:(error instanceof Error?error.message:String(error)).slice(0,4_000)})}finally{this.progress('Cleaning the isolated installation…');try{if(mountedMac){const detached=await runner('hdiutil',['detach',installRoot],{timeoutMs:60_000});if(detached.code!==0)throw new Error(`Qualification disk image detach exited with code ${detached.code}.`);mountedMac=false}if(installedToDisk){const uninstaller=await findUninstaller(installRoot);if(uninstaller){const removed=await runner(uninstaller,['/S'],{timeoutMs:60_000});if(removed.code!==0)throw new Error(`Qualification uninstaller exited with code ${removed.code}.`)}}await safeRemove(testRoot,this.options.root);checks.push({stage:'cleanup',passed:true,detail:'Temporary installation data and registration were removed.'})}catch(error){if(mountedMac)await runner('hdiutil',['detach','-force',installRoot],{timeoutMs:60_000}).catch(()=>{});if(isTransientWindowsLock(error)){scheduleDeferredRemove(testRoot,this.options.root);checks.push({stage:'cleanup',passed:true,detail:'Temporary registration was removed; Windows deferred deletion of a recently locked qualification file.'})}else{await safeRemove(testRoot,this.options.root).catch(()=>{});checks.push({stage:'cleanup',passed:false,detail:(error instanceof Error?error.message:String(error)).slice(0,4_000)})}}}
    return this.finish(id,startedAt,checks,installerPath);
  }
  private progress(message:string):void{this.options.onProgress?.(message)}
  private finish(id:string,startedAt:string,checks:QualificationCheck[],installerPath?:string):QualificationResult{return{id,passed:checks.every(check=>check.passed),startedAt,completedAt:new Date().toISOString(),checks:[...checks],...(installerPath?{installerPath}:{})}}
}

async function findApplicationExecutable(root:string,platform:'windows'|'macos'|'linux'='windows'):Promise<string|undefined>{const entries=await readdir(root,{withFileTypes:true});for(const entry of entries){const path=join(root,entry.name);if(entry.isDirectory()){const nested=await findApplicationExecutable(path,platform);if(nested)return nested}else if(entry.isFile()&&((platform==='windows'&&/\.exe$/i.test(entry.name)&&!/^uninstall/i.test(entry.name)&&(await stat(path)).size>1_000_000)||(platform==='macos'&&path.includes('.app'+sep+'Contents'+sep+'MacOS'+sep))))return path}}
async function findUninstaller(root:string):Promise<string|undefined>{const entries=await readdir(root,{withFileTypes:true});for(const entry of entries){const path=join(root,entry.name);if(entry.isDirectory()){const nested=await findUninstaller(path);if(nested)return nested}else if(entry.isFile()&&/^uninstall.*\.exe$/i.test(entry.name))return path}}
async function safeRemove(target:string,root:string):Promise<void>{const resolvedTarget=resolve(target),resolvedRoot=resolve(root),rel=relative(resolvedRoot,resolvedTarget);if(!rel||rel.startsWith('..')||rel.includes(`..${sep}`))throw new Error('Refused to clean a path outside the qualification root.');await rm(resolvedTarget,{recursive:true,force:true,maxRetries:2,retryDelay:500})}
function delay(ms:number):Promise<void>{return new Promise(resolvePromise=>setTimeout(resolvePromise,ms))}
function applicationLaunchEnvironment():NodeJS.ProcessEnv{const env={...process.env,FOUNDRY_QUALIFICATION:'1'};for(const key of ['ELECTRON_RUN_AS_NODE','FOUNDRY_ELECTRON_BUILDER_CLI','ESBUILD_BINARY_PATH','NODE_OPTIONS','NODE_USE_SYSTEM_CA'])delete env[key];return env}
function isTransientWindowsLock(error:unknown):boolean{return process.platform==='win32'&&error instanceof Error&&/EBUSY|EPERM|resource busy|operation not permitted/i.test(`${(error as NodeJS.ErrnoException).code??''} ${error.message}`)}
function scheduleDeferredRemove(target:string,root:string):void{const retry=setTimeout(()=>{void safeRemove(target,root).catch(()=>{})},30_000);retry.unref()}
function stopProcessTree(pid:number|undefined):Promise<void>{
  if(!pid)return Promise.resolve();
  if(process.platform!=='win32'){try{process.kill(pid,'SIGTERM')}catch{}return Promise.resolve()}
  // Resolve the trusted Windows utility directly instead of consulting PATH.
  // This avoids shell resolution and prevents a project-controlled executable
  // named taskkill from being selected during qualification.
  const taskkill=join(process.env.SystemRoot||'C:\\Windows','System32','taskkill.exe');
  return new Promise(resolvePromise=>{const killer=spawn(taskkill,['/pid',String(pid),'/T','/F'],{shell:false,windowsHide:true,stdio:'ignore'});killer.once('error',()=>resolvePromise());killer.once('exit',()=>resolvePromise())})
}
function runCommand(file:string,args:string[],options:{timeoutMs:number;survivalMs?:number;env?:NodeJS.ProcessEnv}):Promise<CommandResult>{return new Promise((resolvePromise,reject)=>{const child=spawn(file,args,{shell:false,windowsHide:true,env:options.env,stdio:'ignore'});let settled=false,survivalReached=false,survival:NodeJS.Timeout|undefined;const finish=(value:CommandResult)=>{if(settled)return;settled=true;clearTimeout(timeout);if(survival)clearTimeout(survival);resolvePromise(value)},fail=(error:Error)=>{if(settled)return;settled=true;clearTimeout(timeout);if(survival)clearTimeout(survival);reject(error)},timeout=setTimeout(()=>{void stopProcessTree(child.pid).then(()=>fail(new Error('Qualification process timed out.')))},options.timeoutMs);child.once('error',fail);child.once('exit',code=>{if(!survivalReached)finish({code,survived:false})});if(options.survivalMs)survival=setTimeout(()=>{if(child.exitCode===null&&!child.killed){survivalReached=true;void stopProcessTree(child.pid).then(()=>finish({code:null,survived:true}))}},options.survivalMs)})}
function withTimeout<T>(operation:Promise<T>,timeoutMs:number,message:string):Promise<T>{return new Promise((resolvePromise,reject)=>{const timeout=setTimeout(()=>reject(new Error(message)),timeoutMs);operation.then(value=>{clearTimeout(timeout);resolvePromise(value)},error=>{clearTimeout(timeout);reject(error)})})}
