import { safeStorage } from 'electron';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { isProviderId, providerDefinition, providerDefinitions, validateProviderModel, type ProviderCredential, type ProviderId } from './providers.ts';
import { selectBuilderMode, type BuilderMode } from './builder-mode.ts';

type StoredProvider={encryptedApiKey?:string;model?:string};
type StoredHosted={encryptedToken:string;gatewayUrl:string;email:string;credits:number};
type StoredSettings={encryptedApiKey?:string;model?:string;mode?:'hosted'|'byok';hosted?:StoredHosted;activeProvider?:ProviderId;providers?:Partial<Record<ProviderId,StoredProvider>>};
export type ProviderStatus={id:ProviderId;name:string;configured:boolean;model:string;models:string[]};
export type PublicSettings={configured:boolean;mode:'hosted'|'byok';provider:ProviderId;model:string;providers:ProviderStatus[];hosted:{connected:boolean;email:string;credits:number}};

export class SettingsService{
  constructor(private readonly file:string){}
  async publicSettings():Promise<PublicSettings>{const value=this.migrate(await this.read()),mode=value.mode==='hosted'?'hosted':'byok',provider=mode==='hosted'?'openai':isProviderId(value.activeProvider)?value.activeProvider:'openai',providers=providerDefinitions.map(definition=>{const stored=value.providers?.[definition.id];return{id:definition.id,name:definition.name,configured:Boolean(stored?.encryptedApiKey),model:stored?.model&&definition.models.includes(stored.model)?stored.model:definition.defaultModel,models:definition.models}}),active=providers.find(item=>item.id===provider)!,hosted={connected:Boolean(value.hosted?.encryptedToken),email:value.hosted?.email??'',credits:value.hosted?.credits??0};return{configured:mode==='hosted'?hosted.connected:active.configured,mode,provider,model:active.model,providers,hosted}}
  async saveProvider(provider:ProviderId,apiKey:string,model:string):Promise<PublicSettings>{const key=apiKey.trim();if(key.length<16)throw new Error(`Enter a valid ${providerDefinition(provider).name} API key.`);validateProviderModel(provider,model);if(!safeStorage.isEncryptionAvailable())throw new Error('Secure credential storage is unavailable on this device.');const settings=this.migrate(await this.read());settings.providers??={};settings.providers[provider]={encryptedApiKey:safeStorage.encryptString(key).toString('base64'),model};settings.activeProvider=provider;settings.mode='byok';delete settings.encryptedApiKey;delete settings.model;await this.write(settings);return this.publicSettings()}
  async selectProvider(provider:ProviderId,model:string):Promise<PublicSettings>{validateProviderModel(provider,model);const settings=this.migrate(await this.read());settings.providers??={};settings.providers[provider]={...settings.providers[provider],model};settings.activeProvider=provider;await this.write(settings);return this.publicSettings()}
  async clearProvider(provider:ProviderId):Promise<PublicSettings>{const settings=this.migrate(await this.read());if(settings.providers)delete settings.providers[provider];await this.write(settings);return this.publicSettings()}
  async saveHostedSession(value:{token:string;gatewayUrl:string;email:string;credits:number}):Promise<PublicSettings>{if(!safeStorage.isEncryptionAvailable())throw new Error('Secure credential storage is unavailable on this device.');if(!/^https:\/\//.test(value.gatewayUrl)&&!/^http:\/\/127\.0\.0\.1(?::\d+)?$/.test(value.gatewayUrl))throw new Error('Foundry Cloud requires a secure gateway URL.');const settings=this.migrate(await this.read());settings.hosted={encryptedToken:safeStorage.encryptString(value.token).toString('base64'),gatewayUrl:value.gatewayUrl.replace(/\/$/,''),email:value.email,credits:value.credits};settings.mode='hosted';await this.write(settings);return this.publicSettings()}
  async useMode(mode:BuilderMode):Promise<PublicSettings>{const settings=this.migrate(await this.read());settings.mode=selectBuilderMode(mode);await this.write(settings);return this.publicSettings()}
  async clearHosted():Promise<PublicSettings>{const settings=this.migrate(await this.read());delete settings.hosted;settings.mode='byok';await this.write(settings);return this.publicSettings()}
  async hostedAccess():Promise<{token:string;gatewayUrl:string}>{const settings=this.migrate(await this.read());if(!settings.hosted?.encryptedToken)throw new Error('Sign in to Foundry Cloud first.');if(!safeStorage.isEncryptionAvailable())throw new Error('Secure credential storage is unavailable.');return{token:safeStorage.decryptString(Buffer.from(settings.hosted.encryptedToken,'base64')),gatewayUrl:settings.hosted.gatewayUrl}}
  async updateHostedCredits(credits:number):Promise<PublicSettings>{if(!Number.isInteger(credits)||credits<0)throw new Error('Foundry Cloud returned an invalid credit balance.');const settings=this.migrate(await this.read());if(!settings.hosted)throw new Error('Sign in to Foundry Cloud first.');settings.hosted.credits=credits;await this.write(settings);return this.publicSettings()}
  async credential():Promise<ProviderCredential>{const settings=this.migrate(await this.read()),provider=settings.mode==='hosted'?'openai':isProviderId(settings.activeProvider)?settings.activeProvider:'openai',stored=settings.providers?.[provider],definition=providerDefinition(provider);if(settings.mode==='hosted'){if(!settings.hosted?.encryptedToken)throw new Error('Sign in to Foundry Cloud before running the agent.');if(!safeStorage.isEncryptionAvailable())throw new Error('Secure credential storage is unavailable.');return{provider,apiKey:safeStorage.decryptString(Buffer.from(settings.hosted.encryptedToken,'base64')),model:stored?.model&&definition.models.includes(stored.model)?stored.model:definition.defaultModel,mode:'hosted',gatewayUrl:settings.hosted.gatewayUrl}}if(!stored?.encryptedApiKey)throw new Error(`Add a ${definition.name} API key in Settings before running the agent.`);if(!safeStorage.isEncryptionAvailable())throw new Error('Secure credential storage is unavailable.');return{provider,apiKey:safeStorage.decryptString(Buffer.from(stored.encryptedApiKey,'base64')),model:stored.model&&definition.models.includes(stored.model)?stored.model:definition.defaultModel,mode:'byok'}}
  private async read():Promise<StoredSettings>{try{return JSON.parse(await readFile(this.file,'utf8')) as StoredSettings}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return{};throw error}}
  private async write(value:StoredSettings):Promise<void>{await mkdir(dirname(this.file),{recursive:true});await writeFile(this.file,JSON.stringify(value,null,2),'utf8')}
  private migrate(value:StoredSettings):StoredSettings{if(value.encryptedApiKey&&!value.providers?.openai)value.providers={...(value.providers??{}),openai:{encryptedApiKey:value.encryptedApiKey,model:value.model||providerDefinition('openai').defaultModel}};return value}
}
