import { mkdir, readFile, readdir, realpath, stat, writeFile } from 'node:fs/promises';
import { basename, extname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { randomUUID } from 'node:crypto';
import { projectTemplates, type TemplateId } from '../templates.ts';

export type ProjectRecord={id:string;name:string;root:string;createdAt:string;updatedAt:string};
export type ProjectFile={path:string;size:number};
export type ActivityEntry={id:string;at:string;type:'project.created'|'file.written'|'runtime.error'|'agent.failure'|'installer.failure'|'capability.notification';path?:string;detail?:string};

const MAX_TEXT_BYTES=1_000_000;
const IGNORED_DIRS=new Set(['.git','.foundry','node_modules','out','dist','dist-installer','target']);
const TEXT_EXTENSIONS=new Set(['.css','.html','.js','.json','.jsx','.md','.mjs','.scss','.ts','.tsx','.txt','.toml','.yml','.yaml']);
const TEXT_FILENAMES=new Set(['.gitignore','.npmrc','.prettierignore']);
const LEGACY_DESKTOP_TYPES="export {};declare global{interface Window{foundryDesktop?:{openTextFile():Promise<{name:string;content:string}|null>;saveTextFile(content:string,suggestedName?:string):Promise<boolean>}}}\n";
const LEGACY_DESKTOP_TYPES_V2="export {};declare global{interface Window{foundryDesktop?:{openTextFile():Promise<{name:string;content:string}|null>;saveTextFile(content:string,suggestedName?:string):Promise<boolean>;writeClipboardText(text:string):Promise<boolean>;showNotification(title:string,body?:string):Promise<boolean>}}}\n";
const LEGACY_DESKTOP_TYPES_V3="export {};declare global{interface Window{foundryDesktop?:{openTextFile():Promise<{name:string;content:string}|null>;saveTextFile(content:string,suggestedName?:string):Promise<boolean>;chooseFolder():Promise<{name:string;files:{path:string;size:number}[];truncated:boolean}|null>;database:{get(namespace:string,key:string):Promise<unknown|null>;set(namespace:string,key:string,value:unknown):Promise<boolean>;delete(namespace:string,key:string):Promise<boolean>;list(namespace:string):Promise<{key:string;value:unknown;updatedAt:string}[]>};writeClipboardText(text:string):Promise<boolean>;showNotification(title:string,body?:string):Promise<boolean>}}}\n";
const LEGACY_DESKTOP_TYPES_V4="export {};declare global{interface Window{foundryDesktop?:{openTextFile():Promise<{name:string;content:string}|null>;saveTextFile(content:string,suggestedName?:string):Promise<boolean>;chooseFolder():Promise<{name:string;files:{path:string;size:number}[];truncated:boolean}|null>;database:{get(namespace:string,key:string):Promise<unknown|null>;set(namespace:string,key:string,value:unknown):Promise<boolean>;delete(namespace:string,key:string):Promise<boolean>;list(namespace:string):Promise<{key:string;value:unknown;updatedAt:string}[]>};writeClipboardText(text:string):Promise<boolean>;showNotification(title:string,body?:string):Promise<boolean>;tray:{configure(tooltip:string,items:{id:string;label:string}[]):Promise<boolean>;onAction(listener:(id:string)=>void):()=>void};shortcuts:{register(accelerator:string,id:string):Promise<boolean>;clear():Promise<boolean>;onAction(listener:(id:string)=>void):()=>void}}}}\n";
const DESKTOP_TYPES=LEGACY_DESKTOP_TYPES_V4.replace("foundryDesktop?:{",`foundryDesktop?:{ai:{request(payload:Record<string,unknown>):Promise<Record<string,unknown>>};`);
function isEditableTextFile(path:string):boolean{return TEXT_FILENAMES.has(basename(path).toLowerCase())||TEXT_EXTENSIONS.has(extname(path).toLowerCase())}

function safeName(name:string):string{
  const value=name.trim();
  if(value.length<1||value.length>80||/[<>:"/\\|?*\x00-\x1f]/.test(value)||value==='.'||value==='..')throw new Error('Project name must be 1–80 safe filename characters.');
  return value;
}

function contained(root:string,target:string):boolean{
  const rel=relative(resolve(root),resolve(target));
  return rel===''||(!rel.startsWith(`..${sep}`)&&rel!=='..'&&!isAbsolute(rel));
}

export function resolveProjectPath(root:string,projectPath:string):string{
  if(!projectPath||isAbsolute(projectPath)||projectPath.includes('\0'))throw new Error('A relative project path is required.');
  const target=resolve(root,projectPath);
  if(!contained(root,target))throw new Error('Path escapes the active project.');
  return target;
}

async function assertNoSymlink(root:string,target:string):Promise<void>{
  const rootReal=await realpath(root);
  let cursor=target;
  while(contained(root,cursor)){
    try{
      const cursorReal=await realpath(cursor);
      if(!contained(rootReal,cursorReal))throw new Error('Symlink escapes the active project.');
      return;
    }catch(error){
      if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;
      const parent=resolve(cursor,'..');
      if(parent===cursor)break;
      cursor=parent;
    }
  }
  throw new Error('Unable to validate project path.');
}

function templateFiles(name:string,template:TemplateId='blank'):Record<string,string>{const starter=templateSource(name,template);if(template==='tasks')starter.main=starter.main.replace("filter==='All'||filter==='Open'?!task.done:task.done","filter==='All'?true:filter==='Open'?!task.done:task.done");return{
  'package.json':JSON.stringify({name:name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'foundry-app',private:true,version:'0.1.0',scripts:{dev:'vite',build:'tsc && vite build'},dependencies:{'@vitejs/plugin-react':'^5.1.4',vite:'^7.3.6',typescript:'latest',react:'latest','react-dom':'latest'},devDependencies:{'@types/react':'latest','@types/react-dom':'latest'}},null,2)+'\n',
  'index.html':'<!doctype html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>'+name+'</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n',
  'src/main.tsx':starter.main,
  'src/styles.css':starter.css,
  'src/foundry-desktop.d.ts':DESKTOP_TYPES,
  'tsconfig.json':JSON.stringify({compilerOptions:{target:'ES2022',module:'ESNext',moduleResolution:'Bundler',jsx:'react-jsx',strict:true,skipLibCheck:true,noEmit:true},include:['src']},null,2)+'\n',
  'README.md':`# ${name}\n\nCreated with Foundry Desktop.\n`
  ,'.gitignore':'.foundry/\nnode_modules/\nout/\ndist/\ndist-installer/\ntarget/\n'
}}

function workflowTemplate(name:string,kind:'tasks'|'expenses'):{main:string;css:string}{
 const sharedCss=`:root{font-family:Inter,system-ui;color:#f5f6f8;background:#0b0d12}*{box-sizing:border-box}body{margin:0}.app{width:min(980px,calc(100% - 40px));margin:auto;padding:46px 0}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:24px}h1{margin:5px 0;font-size:34px}.eyebrow{color:#ff693b;font-size:10px;font-weight:800;letter-spacing:.15em}.muted{color:#8c929f}form,.panel{padding:20px;border:1px solid #292e38;border-radius:14px;background:#13171d}form{display:grid;grid-template-columns:1fr 160px 140px auto;gap:10px;margin-bottom:16px}input,select,button{height:42px;padding:0 12px;border:1px solid #303641;border-radius:9px;background:#0e1116;color:inherit;font:inherit}button{cursor:pointer}.primary{border-color:#ff693b;background:#ff693b;color:#22100a;font-weight:800}.filters{display:flex;gap:7px;margin-bottom:14px}.filters button{height:32px}.filters .active{border-color:#ff693b;color:#ff8f69}.row{display:grid;grid-template-columns:1fr auto auto;gap:12px;align-items:center;padding:14px 4px;border-bottom:1px solid #272c35}.row:last-child{border:0}.row.done strong{text-decoration:line-through;color:#777f8d}.row button{height:31px}.empty{padding:38px;text-align:center;color:#7f8795}@media(max-width:720px){form{grid-template-columns:1fr}.app{width:calc(100% - 24px)}}`;
 if(kind==='tasks')return{main:`import React,{useEffect,useMemo,useState}from'react';import ReactDOM from'react-dom/client';import'./styles.css';type Task={id:string,title:string,priority:string,done:boolean};const key='foundry.tasks';function App(){const[tasks,setTasks]=useState<Task[]>(()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}),[title,setTitle]=useState(''),[priority,setPriority]=useState('Medium'),[filter,setFilter]=useState('All');useEffect(()=>localStorage.setItem(key,JSON.stringify(tasks)),[tasks]);const visible=useMemo(()=>tasks.filter(task=>filter==='All'||filter==='Open'?!task.done:task.done),[tasks,filter]);function add(e:React.FormEvent){e.preventDefault();if(!title.trim())return;setTasks(items=>[{id:crypto.randomUUID(),title:title.trim(),priority,done:false},...items]);setTitle('')}return <div className="app"><header><div><span className="eyebrow">LOCAL WORKSPACE</span><h1>${name}</h1><span className="muted">{tasks.filter(task=>!task.done).length} tasks remaining</span></div></header><form onSubmit={add}><input aria-label="Task name" placeholder="Task name" value={title} onChange={e=>setTitle(e.target.value)}/><select aria-label="Priority" value={priority} onChange={e=>setPriority(e.target.value)}><option>Low</option><option>Medium</option><option>High</option></select><span/><button className="primary">Add task</button></form><section className="panel"><div className="filters">{['All','Open','Completed'].map(value=><button className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value}</button>)}</div>{visible.length?visible.map(task=><div className={'row '+(task.done?'done':'')} key={task.id}><strong>{task.title}</strong><span className="muted">{task.priority}</span><button onClick={()=>setTasks(items=>items.map(item=>item.id===task.id?{...item,done:!item.done}:item))}>{task.done?'Reopen':'Complete'}</button></div>):<div className="empty">Add your first task.</div>}</section></div>}ReactDOM.createRoot(document.getElementById('root')!).render(<App/>);`,css:sharedCss};
 return{main:`import React,{useEffect,useMemo,useState}from'react';import ReactDOM from'react-dom/client';import'./styles.css';type Expense={id:string,description:string,amount:number,category:string};const key='foundry.expenses';function App(){const[items,setItems]=useState<Expense[]>(()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}),[description,setDescription]=useState(''),[amount,setAmount]=useState(''),[category,setCategory]=useState('Food');useEffect(()=>localStorage.setItem(key,JSON.stringify(items)),[items]);const total=useMemo(()=>items.reduce((sum,item)=>sum+item.amount,0),[items]);function add(e:React.FormEvent){e.preventDefault();const value=Number(amount);if(!description.trim()||value<=0)return;setItems(list=>[{id:crypto.randomUUID(),description:description.trim(),amount:value,category},...list]);setDescription('');setAmount('')}return <div className="app"><header><div><span className="eyebrow">PERSONAL FINANCE</span><h1>${name}</h1><span className="muted">Saved locally</span></div><h1>$${'${'}total.toFixed(2)}</h1></header><form onSubmit={add}><input aria-label="Description" placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><input aria-label="Amount" type="number" min="0.01" step="0.01" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><select aria-label="Category" value={category} onChange={e=>setCategory(e.target.value)}><option>Food</option><option>Transport</option><option>Bills</option><option>Other</option></select><button className="primary">Add expense</button></form><section className="panel">{items.length?items.map(item=><div className="row" key={item.id}><strong>{item.description}</strong><span className="muted">{item.category}</span><b>$${'${'}item.amount.toFixed(2)}</b></div>):<div className="empty">Add your first expense.</div>}</section></div>}ReactDOM.createRoot(document.getElementById('root')!).render(<App/>);`,css:sharedCss};
}

function templateSource(name:string,template:TemplateId):{main:string;css:string}{
  if(template==='tasks'||template==='expenses')return workflowTemplate(name,template);
  if(template==='notes')return{main:`import React,{useMemo,useState}from'react';import ReactDOM from'react-dom/client';import'./styles.css';type Note={id:number;title:string;body:string};const initial:Note[]=[{id:1,title:'Welcome to ${name}',body:'Select a note and start writing.'},{id:2,title:'Ideas',body:'Use Foundry to shape this starter into your own app.'}];function App(){const[notes,setNotes]=useState(initial),[selected,setSelected]=useState(1),[query,setQuery]=useState('');const visible=useMemo(()=>notes.filter(n=>n.title.toLowerCase().includes(query.toLowerCase())),[notes,query]),note=notes.find(n=>n.id===selected);function add(){const next={id:Date.now(),title:'Untitled',body:''};setNotes(v=>[next,...v]);setSelected(next.id)}function update(key:'title'|'body',value:string){setNotes(v=>v.map(n=>n.id===selected?{...n,[key]:value}:n))}return <div className="app"><aside><h1>${name}</h1><button onClick={add}>+ New note</button><input placeholder="Search notes" value={query} onChange={e=>setQuery(e.target.value)}/>{visible.map(n=><button className={n.id===selected?'active':''} onClick={()=>setSelected(n.id)} key={n.id}>{n.title}</button>)}</aside><main>{note?<><input className="title" value={note.title} onChange={e=>update('title',e.target.value)}/><textarea value={note.body} onChange={e=>update('body',e.target.value)}/></>:<p>Create a note to begin.</p>}</main></div>}ReactDOM.createRoot(document.getElementById('root')!).render(<App/>);\n`,css:`:root{font-family:Inter,system-ui;color:#f5f6f8;background:#0b0d12}*{box-sizing:border-box}body{margin:0}.app{display:grid;grid-template-columns:280px 1fr;min-height:100vh}aside{padding:24px;border-right:1px solid #292d36;background:#11141a}h1{font-size:20px}button,input,textarea{font:inherit}aside>button,aside>input{width:100%;margin:5px 0;padding:11px;border:1px solid #303641;border-radius:8px;background:#191d25;color:inherit;text-align:left}aside>button:first-of-type{background:#ff6934;color:#1d0d07;font-weight:800}.active{border-color:#ff6934}main{display:grid;grid-template-rows:auto 1fr;gap:18px;padding:48px}.title,textarea{border:0;outline:0;background:transparent;color:inherit}.title{font-size:38px;font-weight:800}textarea{resize:none;line-height:1.8}\n`};
  if(template==='dashboard')return{main:`import React from'react';import ReactDOM from'react-dom/client';import'./styles.css';const cards=[['Revenue','$24,860','+12.5%'],['Customers','1,429','+8.2%'],['Orders','386','+4.1%']];function App(){return <div className="shell"><aside><h1>${name}</h1>{['Overview','Analytics','Customers','Settings'].map((x,i)=><button className={i===0?'active':''}>{x}</button>)}</aside><main><header><div><small>OVERVIEW</small><h2>Good morning</h2></div><button>Export report</button></header><section className="cards">{cards.map(c=><article><span>{c[0]}</span><strong>{c[1]}</strong><em>{c[2]}</em></article>)}</section><section className="panel"><h3>Recent activity</h3>{['New customer joined','Order #1048 completed','Monthly report generated'].map((x,i)=><p><i/> {x}<time>{i+1}h ago</time></p>)}</section></main></div>}ReactDOM.createRoot(document.getElementById('root')!).render(<App/>);\n`,css:`:root{font-family:Inter,system-ui;color:#edf0f5;background:#0a0c10}*{box-sizing:border-box}body{margin:0}.shell{display:grid;grid-template-columns:230px 1fr;min-height:100vh}aside{padding:25px;background:#11141a;border-right:1px solid #292e38}aside h1{margin:0 0 35px}button{font:inherit}aside button{display:block;width:100%;padding:11px;border:0;border-radius:7px;background:transparent;color:#8992a3;text-align:left}.active{background:#20252f;color:#fff}main{padding:40px}header{display:flex;justify-content:space-between;align-items:center}small{color:#ff6934;font-weight:800;letter-spacing:.15em}h2{font-size:32px;margin:8px 0}header button{padding:10px 15px;border:0;border-radius:7px;background:#ff6934;font-weight:800}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:30px 0}.cards article,.panel{padding:22px;border:1px solid #292e38;border-radius:12px;background:#141820}.cards span{display:block;color:#8d96a6}.cards strong{display:block;margin:12px 0;font-size:28px}.cards em{color:#55d697}.panel p{display:flex;padding:14px 0;border-bottom:1px solid #252a33}.panel i{width:8px;height:8px;margin:6px 12px 0 0;border-radius:50%;background:#ff6934}.panel time{margin-left:auto;color:#7e8797}\n`};
  return{main:`import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport './styles.css';\n\nfunction App(){return <main><p className="eyebrow">BUILT WITH FOUNDRY</p><h1>${name}</h1><p>Your desktop app is ready for its first prompt.</p></main>}\n\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);\n`,css:':root{font-family:Inter,system-ui,sans-serif;color:#f4f5f7;background:#0b0d12}body{margin:0}main{min-height:100vh;display:grid;place-content:center;padding:48px}h1{font-size:56px;margin:8px 0}.eyebrow{color:#ff6934;font-size:11px;font-weight:800;letter-spacing:.16em}p{color:#9da3ae}\n'};
}

export class WorkspaceService{
  private readonly registryFile:string;
  constructor(registryFile:string){this.registryFile=registryFile}
  private async readRegistry():Promise<ProjectRecord[]>{try{return JSON.parse(await readFile(this.registryFile,'utf8')) as ProjectRecord[]}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return[];throw error}}
  private async writeRegistry(projects:ProjectRecord[]):Promise<void>{await mkdir(resolve(this.registryFile,'..'),{recursive:true});await writeFile(this.registryFile,JSON.stringify(projects,null,2),'utf8')}
  async listProjects():Promise<ProjectRecord[]>{const projects=await this.readRegistry();await Promise.all(projects.map(project=>this.ensureBridgeTypes(project)));return projects}
  async createProject(parent:string,nameInput:string,template:TemplateId='blank'):Promise<ProjectRecord>{
    const name=safeName(nameInput),parentReal=await realpath(parent),root=join(parentReal,name);
    if(!projectTemplates.some(item=>item.id===template))throw new Error('Unknown project template.');
    if(!contained(parentReal,root))throw new Error('Invalid project location.');
    await mkdir(root);
    for(const[path,content]of Object.entries(templateFiles(name,template))){const target=resolveProjectPath(root,path);await mkdir(resolve(target,'..'),{recursive:true});await writeFile(target,content,'utf8')}
    await mkdir(join(root,'.foundry'));
    const now=new Date().toISOString(),project={id:randomUUID(),name,root,createdAt:now,updatedAt:now};
    const projects=await this.readRegistry();await this.writeRegistry([project,...projects.filter(item=>item.root!==root)]);await this.log(project,{id:randomUUID(),at:now,type:'project.created'});return project;
  }
  async registerProject(rootInput:string):Promise<ProjectRecord>{
    const root=await realpath(rootInput),info=await stat(root);if(!info.isDirectory())throw new Error('Project root must be a directory.');
    const now=new Date().toISOString(),projects=await this.readRegistry(),existing=projects.find(item=>item.root===root),project=existing?{...existing,updatedAt:now}:{id:randomUUID(),name:basename(root),root,createdAt:now,updatedAt:now};await this.writeRegistry([project,...projects.filter(item=>item.root!==root)]);return project;
  }
  private async ensureBridgeTypes(project:ProjectRecord):Promise<void>{const target=join(project.root,'src','foundry-desktop.d.ts');try{const current=await readFile(target,'utf8');if([LEGACY_DESKTOP_TYPES,LEGACY_DESKTOP_TYPES_V2,LEGACY_DESKTOP_TYPES_V3,LEGACY_DESKTOP_TYPES_V4].includes(current))await writeFile(target,DESKTOP_TYPES,'utf8')}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error}}
  async listFiles(project:ProjectRecord):Promise<ProjectFile[]>{
    const files:ProjectFile[]=[];const walk=async(dir:string):Promise<void>=>{for(const entry of await readdir(dir,{withFileTypes:true})){if(entry.isSymbolicLink())continue;if(entry.isDirectory()&&IGNORED_DIRS.has(entry.name))continue;const absolute=join(dir,entry.name);if(entry.isDirectory())await walk(absolute);else if(entry.isFile()){const info=await stat(absolute);files.push({path:relative(project.root,absolute).split(sep).join('/'),size:info.size})}}};await walk(project.root);return files.sort((a,b)=>a.path.localeCompare(b.path));
  }
  async readText(project:ProjectRecord,path:string):Promise<string>{const target=resolveProjectPath(project.root,path);await assertNoSymlink(project.root,target);const info=await stat(target);if(!info.isFile()||info.size>MAX_TEXT_BYTES)throw new Error('File is not a supported text file.');if(!isEditableTextFile(target))throw new Error('File type is not editable.');const content=await readFile(target,'utf8');if(content.includes('\0'))throw new Error('Binary files are not supported.');return content}
  async writeText(project:ProjectRecord,path:string,content:string):Promise<void>{if(Buffer.byteLength(content,'utf8')>MAX_TEXT_BYTES)throw new Error('File exceeds the 1 MB text limit.');const target=resolveProjectPath(project.root,path);if(!isEditableTextFile(target))throw new Error('File type is not editable.');await assertNoSymlink(project.root,target);await mkdir(resolve(target,'..'),{recursive:true});await writeFile(target,content,'utf8');await this.log(project,{id:randomUUID(),at:new Date().toISOString(),type:'file.written',path})}
  async activity(project:ProjectRecord):Promise<ActivityEntry[]>{try{return(await readFile(join(project.root,'.foundry','activity.jsonl'),'utf8')).trim().split('\n').filter(Boolean).map(line=>JSON.parse(line) as ActivityEntry).reverse()}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return[];throw error}}
  async record(project:ProjectRecord,type:Extract<ActivityEntry['type'],'runtime.error'|'agent.failure'|'installer.failure'|'capability.notification'>,detail:string):Promise<void>{await this.log(project,{id:randomUUID(),at:new Date().toISOString(),type,detail:detail.slice(0,2000)})}
  private async log(project:ProjectRecord,entry:ActivityEntry):Promise<void>{const file=join(project.root,'.foundry','activity.jsonl');let previous='';try{previous=await readFile(file,'utf8')}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error}await writeFile(file,previous+JSON.stringify(entry)+'\n','utf8')}
}
