import { createHash, randomUUID } from 'node:crypto';
import type { IncomingMessage, ServerResponse } from 'node:http';
import type { GatewayStore } from './store.ts';

export type RequestContext={requestId:string;ip:string;startedAt:number};
export function requestContext(request:IncomingMessage):RequestContext{const supplied=request.headers['x-request-id'],requestId=typeof supplied==='string'&&/^[a-zA-Z0-9._-]{8,100}$/.test(supplied)?supplied:randomUUID(),forwarded=request.headers['x-forwarded-for'],candidate=process.env.FOUNDRY_TRUST_PROXY==='1'&&typeof forwarded==='string'?forwarded.split(',')[0]:request.socket.remoteAddress||'unknown',ip=candidate.trim().replace(/^::ffff:/,'');return{requestId,ip:/^[a-fA-F0-9:.]{2,64}$/.test(ip)?ip:'unknown',startedAt:Date.now()}}
export function secureHeaders(response:ServerResponse,context:RequestContext):void{response.setHeader('Cache-Control','no-store');response.setHeader('Content-Security-Policy',"default-src 'none'; frame-ancestors 'none'");response.setHeader('Cross-Origin-Resource-Policy','same-origin');response.setHeader('Referrer-Policy','no-referrer');response.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');response.setHeader('X-Content-Type-Options','nosniff');response.setHeader('X-Frame-Options','DENY');response.setHeader('X-Request-Id',context.requestId)}
export function enforceRateLimit(store:GatewayStore,context:RequestContext,path:string,response:ServerResponse):boolean{const auth=path.startsWith('/v1/auth/'),webhook=path==='/v1/billing/webhook',policy=auth?{limit:12,seconds:900}:webhook?{limit:300,seconds:60}:{limit:120,seconds:60},result=store.consumeRateLimit(`${auth?'auth':webhook?'webhook':'api'}:${context.ip}`,policy.limit,policy.seconds);response.setHeader('RateLimit-Limit',String(policy.limit));response.setHeader('RateLimit-Remaining',String(result.remaining));response.setHeader('RateLimit-Reset',String(result.resetAt));if(result.allowed)return true;response.setHeader('Retry-After',String(Math.max(1,result.resetAt-Math.floor(Date.now()/1000))));response.writeHead(429,{'Content-Type':'application/json'}).end(JSON.stringify({error:'Too many requests. Try again shortly.',requestId:context.requestId}));return false}
export function audit(context:RequestContext,method:string,path:string,status:number):void{const clientHash=createHash('sha256').update(`${process.env.FOUNDRY_LOG_SALT||'local-development'}:${context.ip}`).digest('hex').slice(0,16);process.stdout.write(`${JSON.stringify({time:new Date().toISOString(),level:'info',event:'http_request',requestId:context.requestId,method,path,status,durationMs:Date.now()-context.startedAt,clientHash})}\n`)}
