import { createHash, randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { Pool, type PoolClient } from 'pg';
import type { CreditReservation, GatewayAccount } from './store.ts';
import type { GatewayDataStore, PurchaseRecord, RateLimitResult } from './store-contract.ts';

const scrypt=promisify(scryptCallback);
type Row=Record<string,unknown>;

export class PostgresGatewayStore implements GatewayDataStore{
 private constructor(private readonly pool:Pool,private readonly signupCredits:number){}
 static async connect(connectionString:string,signupCredits=25_000):Promise<PostgresGatewayStore>{
  if(!connectionString)throw new Error('DATABASE_URL is required for PostgreSQL storage.');
  const pool=new Pool({connectionString,max:Number(process.env.FOUNDRY_DATABASE_POOL_SIZE||10),idleTimeoutMillis:30_000,connectionTimeoutMillis:10_000,ssl:process.env.FOUNDRY_DATABASE_SSL==='0'?false:{rejectUnauthorized:false}}),store=new PostgresGatewayStore(pool,signupCredits);
  try{await store.migrate();return store}catch(error){await pool.end();throw error}
 }
 async close():Promise<void>{await this.pool.end()}
 async register(email:string,password:string):Promise<{account:GatewayAccount;token:string}>{const normalized=this.validEmail(email),hash=await this.hashPassword(password),id=randomUUID(),now=new Date().toISOString();return this.transaction(async client=>{try{await client.query('INSERT INTO accounts(id,email,password_hash,credits,monthly_spend_limit,created_at) VALUES($1,$2,$3,$4,$5,$6)',[id,normalized,hash,this.signupCredits,Math.max(this.signupCredits,1),now])}catch(error){if(String(error).includes('23505'))throw new Error('An account with that email already exists.');throw error}await client.query('INSERT INTO ledger(id,account_id,reservation_id,amount,kind,created_at) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),id,null,this.signupCredits,'signup_grant',now]);return{account:await this.account(id,client),token:await this.createSession(id,client)}})}
 async login(email:string,password:string):Promise<{account:GatewayAccount;token:string}>{const normalized=this.validEmail(email),result=await this.pool.query('SELECT id,password_hash FROM accounts WHERE email=$1',[normalized]),row=result.rows[0] as {id:string;password_hash:string}|undefined;if(!row||!await this.verifyPassword(password,row.password_hash))throw new Error('Email or password is incorrect.');return this.transaction(async client=>({account:await this.account(row.id,client),token:await this.createSession(row.id,client)}))}
 async authenticate(token:string):Promise<GatewayAccount>{if(!token||token.length<32)throw new Error('Authentication required.');const result=await this.pool.query('SELECT account_id,expires_at FROM sessions WHERE token_hash=$1',[this.hashToken(token)]),row=result.rows[0] as {account_id:string;expires_at:Date|string}|undefined;if(!row||Date.parse(String(row.expires_at))<=Date.now())throw new Error('Session expired. Sign in again.');return this.account(row.account_id)}
 async reserve(accountId:string,requestId:string,amount:number):Promise<CreditReservation>{this.positiveInteger(amount,'Reservation amount');if(!/^[a-zA-Z0-9_-]{8,120}$/.test(requestId))throw new Error('A valid request ID is required.');return this.transaction(async client=>{const existing=await client.query('SELECT * FROM reservations WHERE account_id=$1 AND request_id=$2 FOR UPDATE',[accountId,requestId]);if(existing.rows[0])return this.reservation(existing.rows[0]);const account=await this.account(accountId,client,true),monthStart=new Date();monthStart.setUTCDate(1);monthStart.setUTCHours(0,0,0,0);const spentResult=await client.query("SELECT COALESCE(-SUM(amount),0)::bigint value FROM ledger WHERE account_id=$1 AND kind='usage' AND created_at >= $2",[accountId,monthStart.toISOString()]),spent=Number(spentResult.rows[0]?.value||0);if(amount>account.credits)throw new Error('Not enough Foundry credits for this build.');if(spent+amount>account.monthlySpendLimit)throw new Error('Monthly AI spend limit reached.');const id=randomUUID(),now=new Date().toISOString();await client.query('UPDATE accounts SET credits=credits-$1 WHERE id=$2',[amount,accountId]);await client.query("INSERT INTO reservations(id,account_id,request_id,reserved,settled,status,created_at) VALUES($1,$2,$3,$4,NULL,'open',$5)",[id,accountId,requestId,amount,now]);return{id,accountId,requestId,reserved:amount,settled:null,status:'open',createdAt:now}})}
 async settle(accountId:string,reservationId:string,actual:number):Promise<CreditReservation>{if(!Number.isInteger(actual)||actual<0)throw new Error('Actual usage must be a non-negative integer.');return this.transaction(async client=>{const result=await client.query('SELECT * FROM reservations WHERE id=$1 AND account_id=$2 FOR UPDATE',[reservationId,accountId]),row=result.rows[0];if(!row)throw new Error('Credit reservation not found.');const current=this.reservation(row);if(current.status!=='open')return current;const charged=Math.min(actual,current.reserved),refund=current.reserved-charged,now=new Date().toISOString();await client.query("UPDATE reservations SET settled=$1,status='settled' WHERE id=$2",[charged,reservationId]);if(refund)await client.query('UPDATE accounts SET credits=credits+$1 WHERE id=$2',[refund,accountId]);if(charged)await client.query('INSERT INTO ledger(id,account_id,reservation_id,amount,kind,created_at) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),accountId,reservationId,-charged,'usage',now]);if(refund)await client.query('INSERT INTO ledger(id,account_id,reservation_id,amount,kind,created_at) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),accountId,reservationId,refund,'reservation_refund',now]);return{...current,settled:charged,status:'settled'}})}
 async release(accountId:string,reservationId:string):Promise<CreditReservation>{return this.transaction(async client=>{const result=await client.query('SELECT * FROM reservations WHERE id=$1 AND account_id=$2 FOR UPDATE',[reservationId,accountId]),row=result.rows[0];if(!row)throw new Error('Credit reservation not found.');const current=this.reservation(row);if(current.status!=='open')return current;await client.query("UPDATE reservations SET settled=0,status='released' WHERE id=$1",[reservationId]);await client.query('UPDATE accounts SET credits=credits+$1 WHERE id=$2',[current.reserved,accountId]);await client.query('INSERT INTO ledger(id,account_id,reservation_id,amount,kind,created_at) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),accountId,reservationId,current.reserved,'reservation_release',new Date().toISOString()]);return{...current,settled:0,status:'released'}})}
 async grantPurchase(value:{eventId:string;accountId:string;sessionId:string;packageId:string;amountPaid:number;currency:string;credits:number}):Promise<GatewayAccount>{this.positiveInteger(value.credits,'Credit grant');if(!Number.isInteger(value.amountPaid)||value.amountPaid<0)throw new Error('Paid amount is invalid.');return this.transaction(async client=>{const existing=await client.query('SELECT account_id FROM purchases WHERE event_id=$1 OR checkout_session_id=$2 FOR UPDATE',[value.eventId,value.sessionId]);if(existing.rows[0])return this.account(String(existing.rows[0].account_id),client);await this.account(value.accountId,client,true);const now=new Date().toISOString();await client.query('INSERT INTO purchases(event_id,account_id,checkout_session_id,package_id,amount_paid,currency,credits,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[value.eventId,value.accountId,value.sessionId,value.packageId,value.amountPaid,value.currency.toLowerCase(),value.credits,now]);await client.query('UPDATE accounts SET credits=credits+$1 WHERE id=$2',[value.credits,value.accountId]);await client.query('INSERT INTO ledger(id,account_id,reservation_id,amount,kind,created_at) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),value.accountId,null,value.credits,'credit_purchase',now]);return this.account(value.accountId,client)})}
 async purchases(accountId:string):Promise<PurchaseRecord[]>{await this.account(accountId);const result=await this.pool.query('SELECT checkout_session_id,package_id,amount_paid,currency,credits,created_at FROM purchases WHERE account_id=$1 ORDER BY created_at DESC LIMIT 100',[accountId]);return result.rows.map(row=>({sessionId:String(row.checkout_session_id),packageId:String(row.package_id),amountPaid:Number(row.amount_paid),currency:String(row.currency),credits:Number(row.credits),createdAt:new Date(row.created_at).toISOString()}))}
 async consumeRateLimit(bucket:string,limit:number,windowSeconds:number,nowSeconds=Math.floor(Date.now()/1000)):Promise<RateLimitResult>{if(!/^[a-zA-Z0-9:._-]{1,200}$/.test(bucket)||!Number.isInteger(limit)||limit<1||!Number.isInteger(windowSeconds)||windowSeconds<1)throw new Error('Invalid rate-limit policy.');const windowStart=Math.floor(nowSeconds/windowSeconds)*windowSeconds;return this.transaction(async client=>{const result=await client.query('SELECT window_start,count FROM rate_limits WHERE bucket=$1 FOR UPDATE',[bucket]),row=result.rows[0] as {window_start:number|string;count:number|string}|undefined,previousStart=Number(row?.window_start),previousCount=Number(row?.count||0);let count=previousStart===windowStart?previousCount:0,allowed=count<limit;if(allowed)count++;await client.query('INSERT INTO rate_limits(bucket,window_start,count) VALUES($1,$2,$3) ON CONFLICT(bucket) DO UPDATE SET window_start=EXCLUDED.window_start,count=EXCLUDED.count',[bucket,windowStart,count]);return{allowed,remaining:Math.max(0,limit-count),resetAt:windowStart+windowSeconds}})}
 private async migrate():Promise<void>{await this.pool.query(`CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,credits BIGINT NOT NULL CHECK(credits>=0),monthly_spend_limit BIGINT NOT NULL CHECK(monthly_spend_limit>=0),created_at TIMESTAMPTZ NOT NULL);CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL);CREATE TABLE IF NOT EXISTS reservations(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,request_id TEXT NOT NULL,reserved BIGINT NOT NULL CHECK(reserved>0),settled BIGINT,status TEXT NOT NULL CHECK(status IN ('open','settled','released')),created_at TIMESTAMPTZ NOT NULL,UNIQUE(account_id,request_id));CREATE TABLE IF NOT EXISTS ledger(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,reservation_id TEXT,amount BIGINT NOT NULL,kind TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL);CREATE TABLE IF NOT EXISTS purchases(event_id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,checkout_session_id TEXT NOT NULL UNIQUE,package_id TEXT NOT NULL,amount_paid BIGINT NOT NULL,currency TEXT NOT NULL,credits BIGINT NOT NULL,created_at TIMESTAMPTZ NOT NULL);CREATE TABLE IF NOT EXISTS rate_limits(bucket TEXT PRIMARY KEY,window_start BIGINT NOT NULL,count BIGINT NOT NULL);CREATE INDEX IF NOT EXISTS sessions_account ON sessions(account_id);CREATE INDEX IF NOT EXISTS ledger_account ON ledger(account_id,created_at);`)}
 private async transaction<T>(operation:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query('BEGIN');const result=await operation(client);await client.query('COMMIT');return result}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
 private async account(id:string,client:Pool|PoolClient=this.pool,lock=false):Promise<GatewayAccount>{const result=await client.query(`SELECT id,email,credits,monthly_spend_limit,created_at FROM accounts WHERE id=$1${lock?' FOR UPDATE':''}`,[id]),row=result.rows[0];if(!row)throw new Error('Account not found.');return{id:String(row.id),email:String(row.email),credits:Number(row.credits),monthlySpendLimit:Number(row.monthly_spend_limit),createdAt:new Date(row.created_at).toISOString()}}
 private reservation(row:Row):CreditReservation{return{id:String(row.id),accountId:String(row.account_id),requestId:String(row.request_id),reserved:Number(row.reserved),settled:row.settled===null?null:Number(row.settled),status:String(row.status) as CreditReservation['status'],createdAt:new Date(row.created_at as string|Date).toISOString()}}
 private async createSession(accountId:string,client:PoolClient):Promise<string>{const token=randomBytes(32).toString('base64url'),now=new Date(),expires=new Date(now.getTime()+30*24*60*60*1000);await client.query('INSERT INTO sessions(token_hash,account_id,expires_at,created_at) VALUES($1,$2,$3,$4)',[this.hashToken(token),accountId,expires.toISOString(),now.toISOString()]);return token}
 private async hashPassword(password:string):Promise<string>{if(password.length<10||password.length>256)throw new Error('Password must be between 10 and 256 characters.');const salt=randomBytes(16),derived=await scrypt(password,salt,32) as Buffer;return `scrypt:${salt.toString('base64')}:${derived.toString('base64')}`}
 private async verifyPassword(password:string,stored:string):Promise<boolean>{const [,saltText,hashText]=stored.split(':');if(!saltText||!hashText)return false;const expected=Buffer.from(hashText,'base64'),actual=await scrypt(password,Buffer.from(saltText,'base64'),expected.length) as Buffer;return actual.length===expected.length&&timingSafeEqual(actual,expected)}
 private hashToken(token:string):string{return createHash('sha256').update(token).digest('hex')}
 private validEmail(value:string):string{const email=value.trim().toLowerCase();if(email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Enter a valid email address.');return email}
 private positiveInteger(value:number,name:string):void{if(!Number.isInteger(value)||value<1||value>1_000_000)throw new Error(`${name} must be a positive integer.`)}
}
