import { createServer } from 'node:http';
import { mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { GatewayService } from './service.ts';
import { GatewayStore } from './store.ts';
import { PostgresGatewayStore } from './postgres-store.ts';
import type { GatewayDataStore } from './store-contract.ts';
import type { ProviderId } from '../providers.ts';
import { BillingService, type StripeMode } from './billing.ts';
import { audit, enforceRateLimit, requestContext, secureHeaders } from './http-security.ts';
import { billingReturnPage } from './billing-pages.ts';

const port=Number(process.env.FOUNDRY_GATEWAY_PORT||8787),databaseFile=resolve(process.env.FOUNDRY_GATEWAY_DATABASE||'data/foundry-gateway.sqlite');
mkdirSync(dirname(databaseFile),{recursive:true});
const keys:Partial<Record<ProviderId,string>>={openai:process.env.OPENAI_API_KEY,anthropic:process.env.ANTHROPIC_API_KEY,google:process.env.GEMINI_API_KEY,xai:process.env.XAI_API_KEY};
const stripeMode=process.env.FOUNDRY_STRIPE_MODE as StripeMode|undefined;if(stripeMode&&stripeMode!=='test'&&stripeMode!=='live')throw new Error('FOUNDRY_STRIPE_MODE must be test or live.');
const signupCredits=Number(process.env.FOUNDRY_SIGNUP_CREDITS||25_000),store:GatewayDataStore=process.env.DATABASE_URL?await PostgresGatewayStore.connect(process.env.DATABASE_URL,signupCredits):new GatewayStore(databaseFile,signupCredits),billing=new BillingService(process.env.STRIPE_SECRET_KEY||'',process.env.STRIPE_WEBHOOK_SECRET||'',process.env.FOUNDRY_BILLING_SUCCESS_URL||'https://foundry.example/billing/success',process.env.FOUNDRY_BILLING_CANCEL_URL||'https://foundry.example/billing/cancel',undefined,fetch,stripeMode),service=new GatewayService(store,keys,fetch,billing,process.env.NODE_ENV==='production');
const host=process.env.FOUNDRY_GATEWAY_HOST||'127.0.0.1';
const server=createServer(async(req,res)=>{const context=requestContext(req),path=(req.url||'/').split('?')[0],method=req.method||'GET';secureHeaders(res,context);if(method==='GET'&&(path==='/billing/success'||path==='/billing/cancel')){res.setHeader('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'none'");res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}).end(billingReturnPage(path.endsWith('success')?'success':'cancel'));audit(context,method,path,200);return}if(!await enforceRateLimit(store,context,path,res)){audit(context,method,path,429);return}let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>14_000_000){res.writeHead(413,{'Content-Type':'application/json'}).end(JSON.stringify({error:'Request body is too large.',requestId:context.requestId}));audit(context,method,path,413);return}}let body:unknown;try{body=raw?JSON.parse(raw):undefined}catch{res.writeHead(400,{'Content-Type':'application/json'}).end(JSON.stringify({error:'Invalid JSON.',requestId:context.requestId}));audit(context,method,path,400);return}const result=await service.handle({method,path,headers:{authorization:req.headers.authorization,'stripe-signature':Array.isArray(req.headers['stripe-signature'])?req.headers['stripe-signature'][0]:req.headers['stripe-signature']},body,rawBody:raw});res.writeHead(result.status,{'Content-Type':'application/json'}).end(JSON.stringify({...result.body as object,requestId:context.requestId}));audit(context,method,path,result.status)});
server.requestTimeout=120_000;server.headersTimeout=15_000;server.keepAliveTimeout=5_000;server.maxHeadersCount=80;
server.listen(port,host,()=>process.stdout.write(`${JSON.stringify({time:new Date().toISOString(),level:'info',event:'gateway_ready',host,port})}\n`));
for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>server.close(async()=>{await store.close();process.exit(0)}));
