import { createHash, randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { promisify } from 'node:util';
import type { AppCredential } from './store-contract.ts';

const scrypt=promisify(scryptCallback);
export type GatewayAccount={id:string;email:string;credits:number;monthlySpendLimit:number;createdAt:string};
export type CreditReservation={id:string;accountId:string;requestId:string;reserved:number;settled:number|null;status:'open'|'settled'|'released';createdAt:string};

export class GatewayStore{
 private readonly database:DatabaseSync;
 constructor(file:string,private readonly signupCredits=25_000){this.database=new DatabaseSync(file);this.database.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
 CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,credits INTEGER NOT NULL CHECK(credits>=0),monthly_spend_limit INTEGER NOT NULL CHECK(monthly_spend_limit>=0),created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS reservations(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,request_id TEXT NOT NULL,reserved INTEGER NOT NULL CHECK(reserved>0),settled INTEGER,status TEXT NOT NULL CHECK(status IN ('open','settled','released')),created_at TEXT NOT NULL,UNIQUE(account_id,request_id));
 CREATE TABLE IF NOT EXISTS ledger(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,reservation_id TEXT,amount INTEGER NOT NULL,kind TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS purchases(event_id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,checkout_session_id TEXT NOT NULL UNIQUE,package_id TEXT NOT NULL,amount_paid INTEGER NOT NULL,currency TEXT NOT NULL,credits INTEGER NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS rate_limits(bucket TEXT PRIMARY KEY,window_start INTEGER NOT NULL,count INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS app_credentials(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,name TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,provider TEXT NOT NULL,model TEXT NOT NULL,monthly_budget INTEGER NOT NULL,requests_per_minute INTEGER NOT NULL,revoked INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,last_used_at TEXT);
 CREATE TABLE IF NOT EXISTS app_usage(id TEXT PRIMARY KEY,credential_id TEXT NOT NULL REFERENCES app_credentials(id) ON DELETE CASCADE,credits INTEGER NOT NULL,created_at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS sessions_account ON sessions(account_id); CREATE INDEX IF NOT EXISTS ledger_account ON ledger(account_id,created_at);`)}
 close():void{this.database.close()}
 async register(email:string,password:string):Promise<{account:GatewayAccount;token:string}>{const normalized=this.validEmail(email),hash=await this.hashPassword(password),id=randomUUID(),now=new Date().toISOString();try{this.database.prepare('INSERT INTO accounts VALUES(?,?,?,?,?,?)').run(id,normalized,hash,this.signupCredits,Math.max(this.signupCredits,1),now);this.database.prepare('INSERT INTO ledger VALUES(?,?,?,?,?,?)').run(randomUUID(),id,null,this.signupCredits,'signup_grant',now)}catch(error){if(String(error).includes('UNIQUE'))throw new Error('An account with that email already exists.');throw error}return{account:this.account(id),token:this.createSession(id)}}
 async login(email:string,password:string):Promise<{account:GatewayAccount;token:string}>{const normalized=this.validEmail(email),row=this.database.prepare('SELECT id,password_hash FROM accounts WHERE email=?').get(normalized) as {id:string;password_hash:string}|undefined;if(!row||!await this.verifyPassword(password,row.password_hash))throw new Error('Email or password is incorrect.');return{account:this.account(row.id),token:this.createSession(row.id)}}
 authenticate(token:string):GatewayAccount{if(!token||token.length<32)throw new Error('Authentication required.');const row=this.database.prepare('SELECT account_id,expires_at FROM sessions WHERE token_hash=?').get(this.hashToken(token)) as {account_id:string;expires_at:string}|undefined;if(!row||Date.parse(row.expires_at)<=Date.now())throw new Error('Session expired. Sign in again.');return this.account(row.account_id)}
 createAppCredential(accountId:string,input:{name:string;provider:AppCredential['provider'];model:string;monthlyBudget:number;requestsPerMinute:number}):{credential:AppCredential;token:string}{this.account(accountId);const name=input.name.trim();if(!name||name.length>80)throw new Error('App credential name is invalid.');this.positiveInteger(input.monthlyBudget,'Monthly app budget');if(!Number.isInteger(input.requestsPerMinute)||input.requestsPerMinute<1||input.requestsPerMinute>120)throw new Error('Requests per minute must be between 1 and 120.');const id=randomUUID(),token=`fapp_${randomBytes(32).toString('base64url')}`,now=new Date().toISOString();this.database.prepare('INSERT INTO app_credentials VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,accountId,name,this.hashToken(token),input.provider,input.model,input.monthlyBudget,input.requestsPerMinute,0,now,null);return{credential:this.appCredential(this.database.prepare('SELECT * FROM app_credentials WHERE id=?').get(id) as Record<string,unknown>),token}}
 listAppCredentials(accountId:string):AppCredential[]{this.account(accountId);return(this.database.prepare('SELECT * FROM app_credentials WHERE account_id=? ORDER BY created_at DESC').all(accountId) as Record<string,unknown>[]).map(row=>this.appCredential(row))}
 revokeAppCredential(accountId:string,id:string):void{const result=this.database.prepare('UPDATE app_credentials SET revoked=1 WHERE id=? AND account_id=?').run(id,accountId);if(!result.changes)throw new Error('App credential not found.')}
 authenticateApp(token:string):AppCredential{if(!token.startsWith('fapp_')||token.length<40)throw new Error('App authentication required.');const row=this.database.prepare('SELECT * FROM app_credentials WHERE token_hash=?').get(this.hashToken(token)) as Record<string,unknown>|undefined;if(!row||Boolean(row.revoked))throw new Error('App credential is invalid or revoked.');this.database.prepare('UPDATE app_credentials SET last_used_at=? WHERE id=?').run(new Date().toISOString(),row.id);return this.appCredential(row)}
 appUsageThisMonth(id:string):number{const start=new Date();start.setUTCDate(1);start.setUTCHours(0,0,0,0);return Number((this.database.prepare('SELECT COALESCE(SUM(credits),0) value FROM app_usage WHERE credential_id=? AND created_at>=?').get(id,start.toISOString()) as {value:number}).value)}
 recordAppUsage(id:string,credits:number):void{this.positiveInteger(credits,'App usage');this.database.prepare('INSERT INTO app_usage VALUES(?,?,?,?)').run(randomUUID(),id,credits,new Date().toISOString())}
 reserve(accountId:string,requestId:string,amount:number):CreditReservation{this.positiveInteger(amount,'Reservation amount');if(!/^[a-zA-Z0-9_-]{8,120}$/.test(requestId))throw new Error('A valid request ID is required.');this.database.exec('BEGIN IMMEDIATE');try{const existing=this.database.prepare('SELECT * FROM reservations WHERE account_id=? AND request_id=?').get(accountId,requestId) as Record<string,unknown>|undefined;if(existing){this.database.exec('COMMIT');return this.reservation(existing)}const account=this.account(accountId),monthStart=new Date();monthStart.setUTCDate(1);monthStart.setUTCHours(0,0,0,0);const spent=(this.database.prepare("SELECT COALESCE(-SUM(amount),0) value FROM ledger WHERE account_id=? AND kind='usage' AND created_at>=?").get(accountId,monthStart.toISOString()) as {value:number}).value;if(amount>account.credits)throw new Error('Not enough Foundry credits for this build.');if(spent+amount>account.monthlySpendLimit)throw new Error('Monthly AI spend limit reached.');const id=randomUUID(),now=new Date().toISOString();this.database.prepare('UPDATE accounts SET credits=credits-? WHERE id=?').run(amount,accountId);this.database.prepare('INSERT INTO reservations VALUES(?,?,?,?,?,?,?)').run(id,accountId,requestId,amount,null,'open',now);this.database.exec('COMMIT');return{id,accountId,requestId,reserved:amount,settled:null,status:'open',createdAt:now}}catch(error){this.database.exec('ROLLBACK');throw error}}
 settle(accountId:string,reservationId:string,actual:number):CreditReservation{if(!Number.isInteger(actual)||actual<0)throw new Error('Actual usage must be a non-negative integer.');this.database.exec('BEGIN IMMEDIATE');try{const row=this.database.prepare('SELECT * FROM reservations WHERE id=? AND account_id=?').get(reservationId,accountId) as Record<string,unknown>|undefined;if(!row)throw new Error('Credit reservation not found.');const current=this.reservation(row);if(current.status!=='open'){this.database.exec('COMMIT');return current}const charged=Math.min(actual,current.reserved),refund=current.reserved-charged,now=new Date().toISOString();this.database.prepare("UPDATE reservations SET settled=?,status='settled' WHERE id=?").run(charged,reservationId);if(refund)this.database.prepare('UPDATE accounts SET credits=credits+? WHERE id=?').run(refund,accountId);if(charged)this.database.prepare('INSERT INTO ledger VALUES(?,?,?,?,?,?)').run(randomUUID(),accountId,reservationId,-charged,'usage',now);if(refund)this.database.prepare('INSERT INTO ledger VALUES(?,?,?,?,?,?)').run(randomUUID(),accountId,reservationId,refund,'reservation_refund',now);this.database.exec('COMMIT');return{...current,settled:charged,status:'settled'}}catch(error){this.database.exec('ROLLBACK');throw error}}
 release(accountId:string,reservationId:string):CreditReservation{this.database.exec('BEGIN IMMEDIATE');try{const row=this.database.prepare('SELECT * FROM reservations WHERE id=? AND account_id=?').get(reservationId,accountId) as Record<string,unknown>|undefined;if(!row)throw new Error('Credit reservation not found.');const current=this.reservation(row);if(current.status!=='open'){this.database.exec('COMMIT');return current}this.database.prepare("UPDATE reservations SET settled=0,status='released' WHERE id=?").run(reservationId);this.database.prepare('UPDATE accounts SET credits=credits+? WHERE id=?').run(current.reserved,accountId);this.database.prepare('INSERT INTO ledger VALUES(?,?,?,?,?,?)').run(randomUUID(),accountId,reservationId,current.reserved,'reservation_release',new Date().toISOString());this.database.exec('COMMIT');return{...current,settled:0,status:'released'}}catch(error){this.database.exec('ROLLBACK');throw error}}
 grantPurchase(value:{eventId:string;accountId:string;sessionId:string;packageId:string;amountPaid:number;currency:string;credits:number}):GatewayAccount{this.positiveInteger(value.credits,'Credit grant');if(!Number.isInteger(value.amountPaid)||value.amountPaid<0)throw new Error('Paid amount is invalid.');this.database.exec('BEGIN IMMEDIATE');try{const existing=this.database.prepare('SELECT account_id FROM purchases WHERE event_id=? OR checkout_session_id=?').get(value.eventId,value.sessionId) as {account_id:string}|undefined;if(existing){this.database.exec('COMMIT');return this.account(existing.account_id)}this.account(value.accountId);const now=new Date().toISOString();this.database.prepare('INSERT INTO purchases VALUES(?,?,?,?,?,?,?,?)').run(value.eventId,value.accountId,value.sessionId,value.packageId,value.amountPaid,value.currency.toLowerCase(),value.credits,now);this.database.prepare('UPDATE accounts SET credits=credits+? WHERE id=?').run(value.credits,value.accountId);this.database.prepare('INSERT INTO ledger VALUES(?,?,?,?,?,?)').run(randomUUID(),value.accountId,null,value.credits,'credit_purchase',now);this.database.exec('COMMIT');return this.account(value.accountId)}catch(error){this.database.exec('ROLLBACK');throw error}}
 purchases(accountId:string):{sessionId:string;packageId:string;amountPaid:number;currency:string;credits:number;createdAt:string}[]{this.account(accountId);return(this.database.prepare('SELECT checkout_session_id,package_id,amount_paid,currency,credits,created_at FROM purchases WHERE account_id=? ORDER BY created_at DESC LIMIT 100').all(accountId) as {checkout_session_id:string;package_id:string;amount_paid:number;currency:string;credits:number;created_at:string}[]).map(row=>({sessionId:row.checkout_session_id,packageId:row.package_id,amountPaid:row.amount_paid,currency:row.currency,credits:row.credits,createdAt:row.created_at}))}
 consumeRateLimit(bucket:string,limit:number,windowSeconds:number,nowSeconds=Math.floor(Date.now()/1000)):{allowed:boolean;remaining:number;resetAt:number}{if(!/^[a-zA-Z0-9:._-]{1,200}$/.test(bucket)||!Number.isInteger(limit)||limit<1||!Number.isInteger(windowSeconds)||windowSeconds<1)throw new Error('Invalid rate-limit policy.');const windowStart=Math.floor(nowSeconds/windowSeconds)*windowSeconds;this.database.exec('BEGIN IMMEDIATE');try{const row=this.database.prepare('SELECT window_start,count FROM rate_limits WHERE bucket=?').get(bucket) as {window_start:number;count:number}|undefined;let count=row?.window_start===windowStart?row.count:0;if(count<limit)count++;this.database.prepare('INSERT INTO rate_limits VALUES(?,?,?) ON CONFLICT(bucket) DO UPDATE SET window_start=excluded.window_start,count=excluded.count').run(bucket,windowStart,count);this.database.exec('COMMIT');return{allowed:count<=limit&&(!row||row.window_start!==windowStart||row.count<limit),remaining:Math.max(0,limit-count),resetAt:windowStart+windowSeconds}}catch(error){this.database.exec('ROLLBACK');throw error}}
 private account(id:string):GatewayAccount{const row=this.database.prepare('SELECT id,email,credits,monthly_spend_limit,created_at FROM accounts WHERE id=?').get(id) as {id:string;email:string;credits:number;monthly_spend_limit:number;created_at:string}|undefined;if(!row)throw new Error('Account not found.');return{id:row.id,email:row.email,credits:row.credits,monthlySpendLimit:row.monthly_spend_limit,createdAt:row.created_at}}
 private reservation(row:Record<string,unknown>):CreditReservation{return{id:String(row.id),accountId:String(row.account_id),requestId:String(row.request_id),reserved:Number(row.reserved),settled:row.settled===null?null:Number(row.settled),status:String(row.status) as CreditReservation['status'],createdAt:String(row.created_at)}}
 private appCredential(row:Record<string,unknown>):AppCredential{return{id:String(row.id),accountId:String(row.account_id),name:String(row.name),provider:String(row.provider) as AppCredential['provider'],model:String(row.model),monthlyBudget:Number(row.monthly_budget),requestsPerMinute:Number(row.requests_per_minute),revoked:Boolean(row.revoked),createdAt:String(row.created_at),lastUsedAt:row.last_used_at?String(row.last_used_at):null}}
 private createSession(accountId:string):string{const token=randomBytes(32).toString('base64url'),now=new Date(),expires=new Date(now.getTime()+30*24*60*60*1000);this.database.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(this.hashToken(token),accountId,expires.toISOString(),now.toISOString());return token}
 private async hashPassword(password:string):Promise<string>{if(password.length<10||password.length>256)throw new Error('Password must be between 10 and 256 characters.');const salt=randomBytes(16),derived=await scrypt(password,salt,32) as Buffer;return `scrypt:${salt.toString('base64')}:${derived.toString('base64')}`}
 private async verifyPassword(password:string,stored:string):Promise<boolean>{const [,saltText,hashText]=stored.split(':');if(!saltText||!hashText)return false;const expected=Buffer.from(hashText,'base64'),actual=await scrypt(password,Buffer.from(saltText,'base64'),expected.length) as Buffer;return actual.length===expected.length&&timingSafeEqual(actual,expected)}
 private hashToken(token:string):string{return createHash('sha256').update(token).digest('hex')}
 private validEmail(value:string):string{const email=value.trim().toLowerCase();if(email.length>254||!/^\S+@\S+\.\S+$/.test(email))throw new Error('Enter a valid email address.');return email}
 private positiveInteger(value:number,name:string):void{if(!Number.isInteger(value)||value<1||value>1_000_000)throw new Error(`${name} must be a positive integer.`)}
}
